/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ResidenceEntity } from '../models';
/**
 * AdminResidenceManagementApi - axios parameter creator
 * @export
 */
export const AdminResidenceManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete a resource
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('_delete', 'id', id)
            const localVarPath = `/api/admin/residences/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new resource
         * @param {ResidenceEntity} residenceEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (residenceEntity: ResidenceEntity, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'residenceEntity' is not null or undefined
            assertParamExists('create', 'residenceEntity', residenceEntity)
            const localVarPath = `/api/admin/residences`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(residenceEntity, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find all resources
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/residences`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find a resource by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('findById', 'id', id)
            const localVarPath = `/api/admin/residences/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a resource
         * @param {number} id 
         * @param {ResidenceEntity} residenceEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update: async (id: number, residenceEntity: ResidenceEntity, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('update', 'id', id)
            // verify required parameter 'residenceEntity' is not null or undefined
            assertParamExists('update', 'residenceEntity', residenceEntity)
            const localVarPath = `/api/admin/residences/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(residenceEntity, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminResidenceManagementApi - functional programming interface
 * @export
 */
export const AdminResidenceManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminResidenceManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Delete a resource
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async _delete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator._delete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminResidenceManagementApi._delete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new resource
         * @param {ResidenceEntity} residenceEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(residenceEntity: ResidenceEntity, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResidenceEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(residenceEntity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminResidenceManagementApi.create']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Find all resources
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ResidenceEntity>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminResidenceManagementApi.findAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Find a resource by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResidenceEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminResidenceManagementApi.findById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a resource
         * @param {number} id 
         * @param {ResidenceEntity} residenceEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(id: number, residenceEntity: ResidenceEntity, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResidenceEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(id, residenceEntity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminResidenceManagementApi.update']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminResidenceManagementApi - factory interface
 * @export
 */
export const AdminResidenceManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminResidenceManagementApiFp(configuration)
    return {
        /**
         * 
         * @summary Delete a resource
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp._delete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new resource
         * @param {ResidenceEntity} residenceEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(residenceEntity: ResidenceEntity, options?: RawAxiosRequestConfig): AxiosPromise<ResidenceEntity> {
            return localVarFp.create(residenceEntity, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find all resources
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<ResidenceEntity>> {
            return localVarFp.findAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find a resource by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ResidenceEntity> {
            return localVarFp.findById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a resource
         * @param {number} id 
         * @param {ResidenceEntity} residenceEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(id: number, residenceEntity: ResidenceEntity, options?: RawAxiosRequestConfig): AxiosPromise<ResidenceEntity> {
            return localVarFp.update(id, residenceEntity, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminResidenceManagementApi - interface
 * @export
 * @interface AdminResidenceManagementApi
 */
export interface AdminResidenceManagementApiInterface {
    /**
     * 
     * @summary Delete a resource
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminResidenceManagementApiInterface
     */
    _delete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Create a new resource
     * @param {ResidenceEntity} residenceEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminResidenceManagementApiInterface
     */
    create(residenceEntity: ResidenceEntity, options?: RawAxiosRequestConfig): AxiosPromise<ResidenceEntity>;

    /**
     * 
     * @summary Find all resources
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminResidenceManagementApiInterface
     */
    findAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<ResidenceEntity>>;

    /**
     * 
     * @summary Find a resource by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminResidenceManagementApiInterface
     */
    findById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ResidenceEntity>;

    /**
     * 
     * @summary Update a resource
     * @param {number} id 
     * @param {ResidenceEntity} residenceEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminResidenceManagementApiInterface
     */
    update(id: number, residenceEntity: ResidenceEntity, options?: RawAxiosRequestConfig): AxiosPromise<ResidenceEntity>;

}

/**
 * AdminResidenceManagementApi - object-oriented interface
 * @export
 * @class AdminResidenceManagementApi
 * @extends {BaseAPI}
 */
export class AdminResidenceManagementApi extends BaseAPI implements AdminResidenceManagementApiInterface {
    /**
     * 
     * @summary Delete a resource
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminResidenceManagementApi
     */
    public _delete(id: number, options?: RawAxiosRequestConfig) {
        return AdminResidenceManagementApiFp(this.configuration)._delete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new resource
     * @param {ResidenceEntity} residenceEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminResidenceManagementApi
     */
    public create(residenceEntity: ResidenceEntity, options?: RawAxiosRequestConfig) {
        return AdminResidenceManagementApiFp(this.configuration).create(residenceEntity, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Find all resources
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminResidenceManagementApi
     */
    public findAll(options?: RawAxiosRequestConfig) {
        return AdminResidenceManagementApiFp(this.configuration).findAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Find a resource by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminResidenceManagementApi
     */
    public findById(id: number, options?: RawAxiosRequestConfig) {
        return AdminResidenceManagementApiFp(this.configuration).findById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a resource
     * @param {number} id 
     * @param {ResidenceEntity} residenceEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminResidenceManagementApi
     */
    public update(id: number, residenceEntity: ResidenceEntity, options?: RawAxiosRequestConfig) {
        return AdminResidenceManagementApiFp(this.configuration).update(id, residenceEntity, options).then((request) => request(this.axios, this.basePath));
    }
}

