/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AdminCreateReportRequest } from '../models';
// @ts-ignore
import type { ReportStatusDTO } from '../models';
/**
 * AdminReportsApi - axios parameter creator
 * @export
 */
export const AdminReportsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Request generation of a new report
         * @summary Create new report
         * @param {AdminCreateReportRequest} adminCreateReportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createReport: async (adminCreateReportRequest: AdminCreateReportRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'adminCreateReportRequest' is not null or undefined
            assertParamExists('createReport', 'adminCreateReportRequest', adminCreateReportRequest)
            const localVarPath = `/api/admin/reports`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adminCreateReportRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Check the status of a report generation request
         * @summary Get report status
         * @param {number} reportId Report ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReportStatus: async (reportId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'reportId' is not null or undefined
            assertParamExists('getReportStatus', 'reportId', reportId)
            const localVarPath = `/api/admin/reports/{reportId}/status`
                .replace(`{${"reportId"}}`, encodeURIComponent(String(reportId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminReportsApi - functional programming interface
 * @export
 */
export const AdminReportsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminReportsApiAxiosParamCreator(configuration)
    return {
        /**
         * Request generation of a new report
         * @summary Create new report
         * @param {AdminCreateReportRequest} adminCreateReportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createReport(adminCreateReportRequest: AdminCreateReportRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReportStatusDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createReport(adminCreateReportRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminReportsApi.createReport']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Check the status of a report generation request
         * @summary Get report status
         * @param {number} reportId Report ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReportStatus(reportId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReportStatusDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReportStatus(reportId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminReportsApi.getReportStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminReportsApi - factory interface
 * @export
 */
export const AdminReportsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminReportsApiFp(configuration)
    return {
        /**
         * Request generation of a new report
         * @summary Create new report
         * @param {AdminCreateReportRequest} adminCreateReportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createReport(adminCreateReportRequest: AdminCreateReportRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReportStatusDTO> {
            return localVarFp.createReport(adminCreateReportRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Check the status of a report generation request
         * @summary Get report status
         * @param {number} reportId Report ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReportStatus(reportId: number, options?: RawAxiosRequestConfig): AxiosPromise<ReportStatusDTO> {
            return localVarFp.getReportStatus(reportId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminReportsApi - interface
 * @export
 * @interface AdminReportsApi
 */
export interface AdminReportsApiInterface {
    /**
     * Request generation of a new report
     * @summary Create new report
     * @param {AdminCreateReportRequest} adminCreateReportRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminReportsApiInterface
     */
    createReport(adminCreateReportRequest: AdminCreateReportRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReportStatusDTO>;

    /**
     * Check the status of a report generation request
     * @summary Get report status
     * @param {number} reportId Report ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminReportsApiInterface
     */
    getReportStatus(reportId: number, options?: RawAxiosRequestConfig): AxiosPromise<ReportStatusDTO>;

}

/**
 * AdminReportsApi - object-oriented interface
 * @export
 * @class AdminReportsApi
 * @extends {BaseAPI}
 */
export class AdminReportsApi extends BaseAPI implements AdminReportsApiInterface {
    /**
     * Request generation of a new report
     * @summary Create new report
     * @param {AdminCreateReportRequest} adminCreateReportRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminReportsApi
     */
    public createReport(adminCreateReportRequest: AdminCreateReportRequest, options?: RawAxiosRequestConfig) {
        return AdminReportsApiFp(this.configuration).createReport(adminCreateReportRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Check the status of a report generation request
     * @summary Get report status
     * @param {number} reportId Report ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminReportsApi
     */
    public getReportStatus(reportId: number, options?: RawAxiosRequestConfig) {
        return AdminReportsApiFp(this.configuration).getReportStatus(reportId, options).then((request) => request(this.axios, this.basePath));
    }
}

