/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CampusEntity } from '../models';
/**
 * AdminCampusManagementApi - axios parameter creator
 * @export
 */
export const AdminCampusManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new resource
         * @param {CampusEntity} campusEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create1: async (campusEntity: CampusEntity, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'campusEntity' is not null or undefined
            assertParamExists('create1', 'campusEntity', campusEntity)
            const localVarPath = `/api/admin/campuses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(campusEntity, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a resource
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delete1: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('delete1', 'id', id)
            const localVarPath = `/api/admin/campuses/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find all resources
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findAll1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/campuses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find a resource by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findById1: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('findById1', 'id', id)
            const localVarPath = `/api/admin/campuses/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a resource
         * @param {number} id 
         * @param {CampusEntity} campusEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update1: async (id: number, campusEntity: CampusEntity, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('update1', 'id', id)
            // verify required parameter 'campusEntity' is not null or undefined
            assertParamExists('update1', 'campusEntity', campusEntity)
            const localVarPath = `/api/admin/campuses/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(campusEntity, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminCampusManagementApi - functional programming interface
 * @export
 */
export const AdminCampusManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminCampusManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new resource
         * @param {CampusEntity} campusEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create1(campusEntity: CampusEntity, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampusEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create1(campusEntity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminCampusManagementApi.create1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a resource
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async delete1(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.delete1(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminCampusManagementApi.delete1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Find all resources
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findAll1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CampusEntity>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findAll1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminCampusManagementApi.findAll1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Find a resource by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findById1(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampusEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findById1(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminCampusManagementApi.findById1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a resource
         * @param {number} id 
         * @param {CampusEntity} campusEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update1(id: number, campusEntity: CampusEntity, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampusEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update1(id, campusEntity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminCampusManagementApi.update1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminCampusManagementApi - factory interface
 * @export
 */
export const AdminCampusManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminCampusManagementApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new resource
         * @param {CampusEntity} campusEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create1(campusEntity: CampusEntity, options?: RawAxiosRequestConfig): AxiosPromise<CampusEntity> {
            return localVarFp.create1(campusEntity, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a resource
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delete1(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.delete1(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find all resources
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findAll1(options?: RawAxiosRequestConfig): AxiosPromise<Array<CampusEntity>> {
            return localVarFp.findAll1(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find a resource by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findById1(id: number, options?: RawAxiosRequestConfig): AxiosPromise<CampusEntity> {
            return localVarFp.findById1(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a resource
         * @param {number} id 
         * @param {CampusEntity} campusEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update1(id: number, campusEntity: CampusEntity, options?: RawAxiosRequestConfig): AxiosPromise<CampusEntity> {
            return localVarFp.update1(id, campusEntity, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminCampusManagementApi - interface
 * @export
 * @interface AdminCampusManagementApi
 */
export interface AdminCampusManagementApiInterface {
    /**
     * 
     * @summary Create a new resource
     * @param {CampusEntity} campusEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminCampusManagementApiInterface
     */
    create1(campusEntity: CampusEntity, options?: RawAxiosRequestConfig): AxiosPromise<CampusEntity>;

    /**
     * 
     * @summary Delete a resource
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminCampusManagementApiInterface
     */
    delete1(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Find all resources
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminCampusManagementApiInterface
     */
    findAll1(options?: RawAxiosRequestConfig): AxiosPromise<Array<CampusEntity>>;

    /**
     * 
     * @summary Find a resource by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminCampusManagementApiInterface
     */
    findById1(id: number, options?: RawAxiosRequestConfig): AxiosPromise<CampusEntity>;

    /**
     * 
     * @summary Update a resource
     * @param {number} id 
     * @param {CampusEntity} campusEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminCampusManagementApiInterface
     */
    update1(id: number, campusEntity: CampusEntity, options?: RawAxiosRequestConfig): AxiosPromise<CampusEntity>;

}

/**
 * AdminCampusManagementApi - object-oriented interface
 * @export
 * @class AdminCampusManagementApi
 * @extends {BaseAPI}
 */
export class AdminCampusManagementApi extends BaseAPI implements AdminCampusManagementApiInterface {
    /**
     * 
     * @summary Create a new resource
     * @param {CampusEntity} campusEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminCampusManagementApi
     */
    public create1(campusEntity: CampusEntity, options?: RawAxiosRequestConfig) {
        return AdminCampusManagementApiFp(this.configuration).create1(campusEntity, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a resource
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminCampusManagementApi
     */
    public delete1(id: number, options?: RawAxiosRequestConfig) {
        return AdminCampusManagementApiFp(this.configuration).delete1(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Find all resources
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminCampusManagementApi
     */
    public findAll1(options?: RawAxiosRequestConfig) {
        return AdminCampusManagementApiFp(this.configuration).findAll1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Find a resource by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminCampusManagementApi
     */
    public findById1(id: number, options?: RawAxiosRequestConfig) {
        return AdminCampusManagementApiFp(this.configuration).findById1(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a resource
     * @param {number} id 
     * @param {CampusEntity} campusEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminCampusManagementApi
     */
    public update1(id: number, campusEntity: CampusEntity, options?: RawAxiosRequestConfig) {
        return AdminCampusManagementApiFp(this.configuration).update1(id, campusEntity, options).then((request) => request(this.axios, this.basePath));
    }
}

