/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AdminFinanceLoadResponse } from '../models';
// @ts-ignore
import type { AdminLoadCreditRequest } from '../models';
// @ts-ignore
import type { AdminLoadCreditResult } from '../models';
// @ts-ignore
import type { AdminTransactionDTO } from '../models';
// @ts-ignore
import type { CompactUserDTO } from '../models';
// @ts-ignore
import type { FinanceUserDTO } from '../models';
// @ts-ignore
import type { FinancialOverview } from '../models';
// @ts-ignore
import type { FinancialPeriodStatistic } from '../models';
/**
 * AdminFinanceApi - axios parameter creator
 * @export
 */
export const AdminFinanceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Load credit to multiple user accounts in bulk
         * @summary Bulk load credit
         * @param {File} csvFile 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkLoadCredit: async (csvFile: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'csvFile' is not null or undefined
            assertParamExists('bulkLoadCredit', 'csvFile', csvFile)
            const localVarPath = `/api/admin/finance/bulk-load`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (csvFile !== undefined) { 
                localVarFormParams.append('csvFile', csvFile as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search transactions
         * @summary Search transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findTransactions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/finance/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search users with financial information using pagination
         * @summary Search users with pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findUsers: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/finance/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search users with financial information using pagination
         * @summary Search users
         * @param {string} query 
         * @param {number} page 
         * @param {number} pageSize 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findUsersSearch: async (query: string, page: number, pageSize: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'query' is not null or undefined
            assertParamExists('findUsersSearch', 'query', query)
            // verify required parameter 'page' is not null or undefined
            assertParamExists('findUsersSearch', 'page', page)
            // verify required parameter 'pageSize' is not null or undefined
            assertParamExists('findUsersSearch', 'pageSize', pageSize)
            const localVarPath = `/api/admin/finance/users/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve financial overview data
         * @summary Get and overview
         * @param {string} start 
         * @param {string} end 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatistics: async (start: string, end: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'start' is not null or undefined
            assertParamExists('getStatistics', 'start', start)
            // verify required parameter 'end' is not null or undefined
            assertParamExists('getStatistics', 'end', end)
            const localVarPath = `/api/admin/finance/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (start !== undefined) {
                localVarQueryParameter['start'] = (start as any instanceof Date) ?
                    (start as any).toISOString() :
                    start;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = (end as any instanceof Date) ?
                    (end as any).toISOString() :
                    end;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve detailed financial information for a specific user
         * @summary Get user financial details
         * @param {number} userId User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserDetail: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserDetail', 'userId', userId)
            const localVarPath = `/api/admin/finance/users/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Load user Credit
         * @summary Load user credit
         * @param {AdminLoadCreditRequest} adminLoadCreditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loadUserCredit: async (adminLoadCreditRequest: AdminLoadCreditRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'adminLoadCreditRequest' is not null or undefined
            assertParamExists('loadUserCredit', 'adminLoadCreditRequest', adminLoadCreditRequest)
            const localVarPath = `/api/admin/finance/load`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adminLoadCreditRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve financial overview data
         * @summary Get and overview
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        overview: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/finance/overview`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminFinanceApi - functional programming interface
 * @export
 */
export const AdminFinanceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminFinanceApiAxiosParamCreator(configuration)
    return {
        /**
         * Load credit to multiple user accounts in bulk
         * @summary Bulk load credit
         * @param {File} csvFile 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkLoadCredit(csvFile: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminFinanceLoadResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkLoadCredit(csvFile, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminFinanceApi.bulkLoadCredit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Search transactions
         * @summary Search transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findTransactions(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AdminTransactionDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findTransactions(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminFinanceApi.findTransactions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Search users with financial information using pagination
         * @summary Search users with pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findUsers(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FinanceUserDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findUsers(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminFinanceApi.findUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Search users with financial information using pagination
         * @summary Search users
         * @param {string} query 
         * @param {number} page 
         * @param {number} pageSize 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findUsersSearch(query: string, page: number, pageSize: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CompactUserDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findUsersSearch(query, page, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminFinanceApi.findUsersSearch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve financial overview data
         * @summary Get and overview
         * @param {string} start 
         * @param {string} end 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatistics(start: string, end: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinancialPeriodStatistic>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStatistics(start, end, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminFinanceApi.getStatistics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve detailed financial information for a specific user
         * @summary Get user financial details
         * @param {number} userId User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserDetail(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinanceUserDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserDetail(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminFinanceApi.getUserDetail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Load user Credit
         * @summary Load user credit
         * @param {AdminLoadCreditRequest} adminLoadCreditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loadUserCredit(adminLoadCreditRequest: AdminLoadCreditRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminLoadCreditResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loadUserCredit(adminLoadCreditRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminFinanceApi.loadUserCredit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve financial overview data
         * @summary Get and overview
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async overview(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinancialOverview>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.overview(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminFinanceApi.overview']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminFinanceApi - factory interface
 * @export
 */
export const AdminFinanceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminFinanceApiFp(configuration)
    return {
        /**
         * Load credit to multiple user accounts in bulk
         * @summary Bulk load credit
         * @param {File} csvFile 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkLoadCredit(csvFile: File, options?: RawAxiosRequestConfig): AxiosPromise<AdminFinanceLoadResponse> {
            return localVarFp.bulkLoadCredit(csvFile, options).then((request) => request(axios, basePath));
        },
        /**
         * Search transactions
         * @summary Search transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findTransactions(options?: RawAxiosRequestConfig): AxiosPromise<Array<AdminTransactionDTO>> {
            return localVarFp.findTransactions(options).then((request) => request(axios, basePath));
        },
        /**
         * Search users with financial information using pagination
         * @summary Search users with pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findUsers(options?: RawAxiosRequestConfig): AxiosPromise<Array<FinanceUserDTO>> {
            return localVarFp.findUsers(options).then((request) => request(axios, basePath));
        },
        /**
         * Search users with financial information using pagination
         * @summary Search users
         * @param {string} query 
         * @param {number} page 
         * @param {number} pageSize 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findUsersSearch(query: string, page: number, pageSize: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<CompactUserDTO>> {
            return localVarFp.findUsersSearch(query, page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve financial overview data
         * @summary Get and overview
         * @param {string} start 
         * @param {string} end 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatistics(start: string, end: string, options?: RawAxiosRequestConfig): AxiosPromise<FinancialPeriodStatistic> {
            return localVarFp.getStatistics(start, end, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve detailed financial information for a specific user
         * @summary Get user financial details
         * @param {number} userId User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserDetail(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<FinanceUserDTO> {
            return localVarFp.getUserDetail(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Load user Credit
         * @summary Load user credit
         * @param {AdminLoadCreditRequest} adminLoadCreditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loadUserCredit(adminLoadCreditRequest: AdminLoadCreditRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminLoadCreditResult> {
            return localVarFp.loadUserCredit(adminLoadCreditRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve financial overview data
         * @summary Get and overview
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        overview(options?: RawAxiosRequestConfig): AxiosPromise<FinancialOverview> {
            return localVarFp.overview(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminFinanceApi - interface
 * @export
 * @interface AdminFinanceApi
 */
export interface AdminFinanceApiInterface {
    /**
     * Load credit to multiple user accounts in bulk
     * @summary Bulk load credit
     * @param {File} csvFile 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApiInterface
     */
    bulkLoadCredit(csvFile: File, options?: RawAxiosRequestConfig): AxiosPromise<AdminFinanceLoadResponse>;

    /**
     * Search transactions
     * @summary Search transactions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApiInterface
     */
    findTransactions(options?: RawAxiosRequestConfig): AxiosPromise<Array<AdminTransactionDTO>>;

    /**
     * Search users with financial information using pagination
     * @summary Search users with pagination
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApiInterface
     */
    findUsers(options?: RawAxiosRequestConfig): AxiosPromise<Array<FinanceUserDTO>>;

    /**
     * Search users with financial information using pagination
     * @summary Search users
     * @param {string} query 
     * @param {number} page 
     * @param {number} pageSize 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApiInterface
     */
    findUsersSearch(query: string, page: number, pageSize: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<CompactUserDTO>>;

    /**
     * Retrieve financial overview data
     * @summary Get and overview
     * @param {string} start 
     * @param {string} end 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApiInterface
     */
    getStatistics(start: string, end: string, options?: RawAxiosRequestConfig): AxiosPromise<FinancialPeriodStatistic>;

    /**
     * Retrieve detailed financial information for a specific user
     * @summary Get user financial details
     * @param {number} userId User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApiInterface
     */
    getUserDetail(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<FinanceUserDTO>;

    /**
     * Load user Credit
     * @summary Load user credit
     * @param {AdminLoadCreditRequest} adminLoadCreditRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApiInterface
     */
    loadUserCredit(adminLoadCreditRequest: AdminLoadCreditRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminLoadCreditResult>;

    /**
     * Retrieve financial overview data
     * @summary Get and overview
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApiInterface
     */
    overview(options?: RawAxiosRequestConfig): AxiosPromise<FinancialOverview>;

}

/**
 * AdminFinanceApi - object-oriented interface
 * @export
 * @class AdminFinanceApi
 * @extends {BaseAPI}
 */
export class AdminFinanceApi extends BaseAPI implements AdminFinanceApiInterface {
    /**
     * Load credit to multiple user accounts in bulk
     * @summary Bulk load credit
     * @param {File} csvFile 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApi
     */
    public bulkLoadCredit(csvFile: File, options?: RawAxiosRequestConfig) {
        return AdminFinanceApiFp(this.configuration).bulkLoadCredit(csvFile, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Search transactions
     * @summary Search transactions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApi
     */
    public findTransactions(options?: RawAxiosRequestConfig) {
        return AdminFinanceApiFp(this.configuration).findTransactions(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Search users with financial information using pagination
     * @summary Search users with pagination
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApi
     */
    public findUsers(options?: RawAxiosRequestConfig) {
        return AdminFinanceApiFp(this.configuration).findUsers(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Search users with financial information using pagination
     * @summary Search users
     * @param {string} query 
     * @param {number} page 
     * @param {number} pageSize 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApi
     */
    public findUsersSearch(query: string, page: number, pageSize: number, options?: RawAxiosRequestConfig) {
        return AdminFinanceApiFp(this.configuration).findUsersSearch(query, page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve financial overview data
     * @summary Get and overview
     * @param {string} start 
     * @param {string} end 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApi
     */
    public getStatistics(start: string, end: string, options?: RawAxiosRequestConfig) {
        return AdminFinanceApiFp(this.configuration).getStatistics(start, end, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve detailed financial information for a specific user
     * @summary Get user financial details
     * @param {number} userId User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApi
     */
    public getUserDetail(userId: number, options?: RawAxiosRequestConfig) {
        return AdminFinanceApiFp(this.configuration).getUserDetail(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Load user Credit
     * @summary Load user credit
     * @param {AdminLoadCreditRequest} adminLoadCreditRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApi
     */
    public loadUserCredit(adminLoadCreditRequest: AdminLoadCreditRequest, options?: RawAxiosRequestConfig) {
        return AdminFinanceApiFp(this.configuration).loadUserCredit(adminLoadCreditRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve financial overview data
     * @summary Get and overview
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFinanceApi
     */
    public overview(options?: RawAxiosRequestConfig) {
        return AdminFinanceApiFp(this.configuration).overview(options).then((request) => request(this.axios, this.basePath));
    }
}

