/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AdminFeedbackDTO } from '../models';
// @ts-ignore
import type { FeedbackItemStatistics } from '../models';
// @ts-ignore
import type { FeedbackPeriodStatistics } from '../models';
// @ts-ignore
import type { FeedbackSentimentRequest } from '../models';
/**
 * AdminFeedbackApi - axios parameter creator
 * @export
 */
export const AdminFeedbackApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve feedback data
         * @summary Get and overview
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllFeedback: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/feedback`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve feedback filtered by period, rating range, and menu item name
         * @summary Get filtered feedback
         * @param {string} start 
         * @param {string} end 
         * @param {number} [minRating] 
         * @param {number} [maxRating] 
         * @param {string} [menuItemName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeedbackFiltered: async (start: string, end: string, minRating?: number, maxRating?: number, menuItemName?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'start' is not null or undefined
            assertParamExists('getFeedbackFiltered', 'start', start)
            // verify required parameter 'end' is not null or undefined
            assertParamExists('getFeedbackFiltered', 'end', end)
            const localVarPath = `/api/admin/feedback/filtered`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (start !== undefined) {
                localVarQueryParameter['start'] = (start as any instanceof Date) ?
                    (start as any).toISOString() :
                    start;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = (end as any instanceof Date) ?
                    (end as any).toISOString() :
                    end;
            }

            if (minRating !== undefined) {
                localVarQueryParameter['minRating'] = minRating;
            }

            if (maxRating !== undefined) {
                localVarQueryParameter['maxRating'] = maxRating;
            }

            if (menuItemName !== undefined) {
                localVarQueryParameter['menuItemName'] = menuItemName;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve aggregated feedback statistics for a specified time period
         * @summary Get feedback statistics for a period
         * @param {string} start 
         * @param {string} end 
         * @param {number} [menuItemId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeedbackStatistics: async (start: string, end: string, menuItemId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'start' is not null or undefined
            assertParamExists('getFeedbackStatistics', 'start', start)
            // verify required parameter 'end' is not null or undefined
            assertParamExists('getFeedbackStatistics', 'end', end)
            const localVarPath = `/api/admin/feedback/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (start !== undefined) {
                localVarQueryParameter['start'] = (start as any instanceof Date) ?
                    (start as any).toISOString() :
                    start;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = (end as any instanceof Date) ?
                    (end as any).toISOString() :
                    end;
            }

            if (menuItemId !== undefined) {
                localVarQueryParameter['menuItemId'] = menuItemId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve feedback statistics grouped by menu item
         * @summary Get feedback statistics by menu item
         * @param {string} start 
         * @param {string} end 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeedbackStatisticsByItem: async (start: string, end: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'start' is not null or undefined
            assertParamExists('getFeedbackStatisticsByItem', 'start', start)
            // verify required parameter 'end' is not null or undefined
            assertParamExists('getFeedbackStatisticsByItem', 'end', end)
            const localVarPath = `/api/admin/feedback/statistics/by-item`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (start !== undefined) {
                localVarQueryParameter['start'] = (start as any instanceof Date) ?
                    (start as any).toISOString() :
                    start;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = (end as any instanceof Date) ?
                    (end as any).toISOString() :
                    end;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Perform sentiment analysis on feedback data
         * @summary Analyze feedback sentiment
         * @param {Array<FeedbackSentimentRequest>} feedbackSentimentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setFeedbackSentiment: async (feedbackSentimentRequest: Array<FeedbackSentimentRequest>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'feedbackSentimentRequest' is not null or undefined
            assertParamExists('setFeedbackSentiment', 'feedbackSentimentRequest', feedbackSentimentRequest)
            const localVarPath = `/api/admin/feedback/sentiment`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(feedbackSentimentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminFeedbackApi - functional programming interface
 * @export
 */
export const AdminFeedbackApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminFeedbackApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve feedback data
         * @summary Get and overview
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllFeedback(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AdminFeedbackDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllFeedback(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminFeedbackApi.getAllFeedback']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve feedback filtered by period, rating range, and menu item name
         * @summary Get filtered feedback
         * @param {string} start 
         * @param {string} end 
         * @param {number} [minRating] 
         * @param {number} [maxRating] 
         * @param {string} [menuItemName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFeedbackFiltered(start: string, end: string, minRating?: number, maxRating?: number, menuItemName?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AdminFeedbackDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFeedbackFiltered(start, end, minRating, maxRating, menuItemName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminFeedbackApi.getFeedbackFiltered']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve aggregated feedback statistics for a specified time period
         * @summary Get feedback statistics for a period
         * @param {string} start 
         * @param {string} end 
         * @param {number} [menuItemId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFeedbackStatistics(start: string, end: string, menuItemId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FeedbackPeriodStatistics>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFeedbackStatistics(start, end, menuItemId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminFeedbackApi.getFeedbackStatistics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve feedback statistics grouped by menu item
         * @summary Get feedback statistics by menu item
         * @param {string} start 
         * @param {string} end 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFeedbackStatisticsByItem(start: string, end: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FeedbackItemStatistics>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFeedbackStatisticsByItem(start, end, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminFeedbackApi.getFeedbackStatisticsByItem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Perform sentiment analysis on feedback data
         * @summary Analyze feedback sentiment
         * @param {Array<FeedbackSentimentRequest>} feedbackSentimentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setFeedbackSentiment(feedbackSentimentRequest: Array<FeedbackSentimentRequest>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setFeedbackSentiment(feedbackSentimentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminFeedbackApi.setFeedbackSentiment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminFeedbackApi - factory interface
 * @export
 */
export const AdminFeedbackApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminFeedbackApiFp(configuration)
    return {
        /**
         * Retrieve feedback data
         * @summary Get and overview
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllFeedback(options?: RawAxiosRequestConfig): AxiosPromise<Array<AdminFeedbackDTO>> {
            return localVarFp.getAllFeedback(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve feedback filtered by period, rating range, and menu item name
         * @summary Get filtered feedback
         * @param {string} start 
         * @param {string} end 
         * @param {number} [minRating] 
         * @param {number} [maxRating] 
         * @param {string} [menuItemName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeedbackFiltered(start: string, end: string, minRating?: number, maxRating?: number, menuItemName?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<AdminFeedbackDTO>> {
            return localVarFp.getFeedbackFiltered(start, end, minRating, maxRating, menuItemName, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve aggregated feedback statistics for a specified time period
         * @summary Get feedback statistics for a period
         * @param {string} start 
         * @param {string} end 
         * @param {number} [menuItemId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeedbackStatistics(start: string, end: string, menuItemId?: number, options?: RawAxiosRequestConfig): AxiosPromise<FeedbackPeriodStatistics> {
            return localVarFp.getFeedbackStatistics(start, end, menuItemId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve feedback statistics grouped by menu item
         * @summary Get feedback statistics by menu item
         * @param {string} start 
         * @param {string} end 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeedbackStatisticsByItem(start: string, end: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<FeedbackItemStatistics>> {
            return localVarFp.getFeedbackStatisticsByItem(start, end, options).then((request) => request(axios, basePath));
        },
        /**
         * Perform sentiment analysis on feedback data
         * @summary Analyze feedback sentiment
         * @param {Array<FeedbackSentimentRequest>} feedbackSentimentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setFeedbackSentiment(feedbackSentimentRequest: Array<FeedbackSentimentRequest>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.setFeedbackSentiment(feedbackSentimentRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminFeedbackApi - interface
 * @export
 * @interface AdminFeedbackApi
 */
export interface AdminFeedbackApiInterface {
    /**
     * Retrieve feedback data
     * @summary Get and overview
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFeedbackApiInterface
     */
    getAllFeedback(options?: RawAxiosRequestConfig): AxiosPromise<Array<AdminFeedbackDTO>>;

    /**
     * Retrieve feedback filtered by period, rating range, and menu item name
     * @summary Get filtered feedback
     * @param {string} start 
     * @param {string} end 
     * @param {number} [minRating] 
     * @param {number} [maxRating] 
     * @param {string} [menuItemName] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFeedbackApiInterface
     */
    getFeedbackFiltered(start: string, end: string, minRating?: number, maxRating?: number, menuItemName?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<AdminFeedbackDTO>>;

    /**
     * Retrieve aggregated feedback statistics for a specified time period
     * @summary Get feedback statistics for a period
     * @param {string} start 
     * @param {string} end 
     * @param {number} [menuItemId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFeedbackApiInterface
     */
    getFeedbackStatistics(start: string, end: string, menuItemId?: number, options?: RawAxiosRequestConfig): AxiosPromise<FeedbackPeriodStatistics>;

    /**
     * Retrieve feedback statistics grouped by menu item
     * @summary Get feedback statistics by menu item
     * @param {string} start 
     * @param {string} end 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFeedbackApiInterface
     */
    getFeedbackStatisticsByItem(start: string, end: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<FeedbackItemStatistics>>;

    /**
     * Perform sentiment analysis on feedback data
     * @summary Analyze feedback sentiment
     * @param {Array<FeedbackSentimentRequest>} feedbackSentimentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFeedbackApiInterface
     */
    setFeedbackSentiment(feedbackSentimentRequest: Array<FeedbackSentimentRequest>, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * AdminFeedbackApi - object-oriented interface
 * @export
 * @class AdminFeedbackApi
 * @extends {BaseAPI}
 */
export class AdminFeedbackApi extends BaseAPI implements AdminFeedbackApiInterface {
    /**
     * Retrieve feedback data
     * @summary Get and overview
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFeedbackApi
     */
    public getAllFeedback(options?: RawAxiosRequestConfig) {
        return AdminFeedbackApiFp(this.configuration).getAllFeedback(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve feedback filtered by period, rating range, and menu item name
     * @summary Get filtered feedback
     * @param {string} start 
     * @param {string} end 
     * @param {number} [minRating] 
     * @param {number} [maxRating] 
     * @param {string} [menuItemName] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFeedbackApi
     */
    public getFeedbackFiltered(start: string, end: string, minRating?: number, maxRating?: number, menuItemName?: string, options?: RawAxiosRequestConfig) {
        return AdminFeedbackApiFp(this.configuration).getFeedbackFiltered(start, end, minRating, maxRating, menuItemName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve aggregated feedback statistics for a specified time period
     * @summary Get feedback statistics for a period
     * @param {string} start 
     * @param {string} end 
     * @param {number} [menuItemId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFeedbackApi
     */
    public getFeedbackStatistics(start: string, end: string, menuItemId?: number, options?: RawAxiosRequestConfig) {
        return AdminFeedbackApiFp(this.configuration).getFeedbackStatistics(start, end, menuItemId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve feedback statistics grouped by menu item
     * @summary Get feedback statistics by menu item
     * @param {string} start 
     * @param {string} end 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFeedbackApi
     */
    public getFeedbackStatisticsByItem(start: string, end: string, options?: RawAxiosRequestConfig) {
        return AdminFeedbackApiFp(this.configuration).getFeedbackStatisticsByItem(start, end, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Perform sentiment analysis on feedback data
     * @summary Analyze feedback sentiment
     * @param {Array<FeedbackSentimentRequest>} feedbackSentimentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminFeedbackApi
     */
    public setFeedbackSentiment(feedbackSentimentRequest: Array<FeedbackSentimentRequest>, options?: RawAxiosRequestConfig) {
        return AdminFeedbackApiFp(this.configuration).setFeedbackSentiment(feedbackSentimentRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

