/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MenuTemplateCreateRequest } from '../models';
// @ts-ignore
import type { MenuTemplateDTO } from '../models';
// @ts-ignore
import type { MenuTemplateUpdateRequest } from '../models';
// @ts-ignore
import type { PresetNameDTO } from '../models';
/**
 * AdminMenuTemplatesApi - axios parameter creator
 * @export
 */
export const AdminMenuTemplatesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a new menu template
         * @summary Create new template
         * @param {MenuTemplateCreateRequest} menuTemplateCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTemplate: async (menuTemplateCreateRequest: MenuTemplateCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'menuTemplateCreateRequest' is not null or undefined
            assertParamExists('createTemplate', 'menuTemplateCreateRequest', menuTemplateCreateRequest)
            const localVarPath = `/api/admin/menu-templates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(menuTemplateCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a menu template by ID
         * @summary Delete template
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTemplate: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteTemplate', 'id', id)
            const localVarPath = `/api/admin/menu-templates/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete all templates for a specific preset name
         * @summary Batch delete templates by preset
         * @param {string} presetName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTemplatesByPresetName: async (presetName: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'presetName' is not null or undefined
            assertParamExists('deleteTemplatesByPresetName', 'presetName', presetName)
            const localVarPath = `/api/admin/menu-templates/preset/{presetName}`
                .replace(`{${"presetName"}}`, encodeURIComponent(String(presetName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve all distinct preset names with metadata
         * @summary Get distinct preset names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDistinctPresetNames: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/menu-templates/presets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve all templates for a specific preset name
         * @summary Get templates by preset name
         * @param {string} presetName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplatesByPresetName: async (presetName: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'presetName' is not null or undefined
            assertParamExists('getTemplatesByPresetName', 'presetName', presetName)
            const localVarPath = `/api/admin/menu-templates/preset/{presetName}`
                .replace(`{${"presetName"}}`, encodeURIComponent(String(presetName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update an existing menu template
         * @summary Update existing template
         * @param {number} id 
         * @param {MenuTemplateUpdateRequest} menuTemplateUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTemplate: async (id: number, menuTemplateUpdateRequest: MenuTemplateUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateTemplate', 'id', id)
            // verify required parameter 'menuTemplateUpdateRequest' is not null or undefined
            assertParamExists('updateTemplate', 'menuTemplateUpdateRequest', menuTemplateUpdateRequest)
            const localVarPath = `/api/admin/menu-templates/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(menuTemplateUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminMenuTemplatesApi - functional programming interface
 * @export
 */
export const AdminMenuTemplatesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminMenuTemplatesApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a new menu template
         * @summary Create new template
         * @param {MenuTemplateCreateRequest} menuTemplateCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTemplate(menuTemplateCreateRequest: MenuTemplateCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MenuTemplateDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTemplate(menuTemplateCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuTemplatesApi.createTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a menu template by ID
         * @summary Delete template
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTemplate(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTemplate(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuTemplatesApi.deleteTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete all templates for a specific preset name
         * @summary Batch delete templates by preset
         * @param {string} presetName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTemplatesByPresetName(presetName: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTemplatesByPresetName(presetName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuTemplatesApi.deleteTemplatesByPresetName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve all distinct preset names with metadata
         * @summary Get distinct preset names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDistinctPresetNames(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PresetNameDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDistinctPresetNames(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuTemplatesApi.getDistinctPresetNames']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve all templates for a specific preset name
         * @summary Get templates by preset name
         * @param {string} presetName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTemplatesByPresetName(presetName: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MenuTemplateDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTemplatesByPresetName(presetName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuTemplatesApi.getTemplatesByPresetName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update an existing menu template
         * @summary Update existing template
         * @param {number} id 
         * @param {MenuTemplateUpdateRequest} menuTemplateUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTemplate(id: number, menuTemplateUpdateRequest: MenuTemplateUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MenuTemplateDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTemplate(id, menuTemplateUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuTemplatesApi.updateTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminMenuTemplatesApi - factory interface
 * @export
 */
export const AdminMenuTemplatesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminMenuTemplatesApiFp(configuration)
    return {
        /**
         * Create a new menu template
         * @summary Create new template
         * @param {MenuTemplateCreateRequest} menuTemplateCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTemplate(menuTemplateCreateRequest: MenuTemplateCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<MenuTemplateDTO> {
            return localVarFp.createTemplate(menuTemplateCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a menu template by ID
         * @summary Delete template
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTemplate(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteTemplate(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete all templates for a specific preset name
         * @summary Batch delete templates by preset
         * @param {string} presetName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTemplatesByPresetName(presetName: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteTemplatesByPresetName(presetName, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve all distinct preset names with metadata
         * @summary Get distinct preset names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDistinctPresetNames(options?: RawAxiosRequestConfig): AxiosPromise<Array<PresetNameDTO>> {
            return localVarFp.getDistinctPresetNames(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve all templates for a specific preset name
         * @summary Get templates by preset name
         * @param {string} presetName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplatesByPresetName(presetName: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuTemplateDTO>> {
            return localVarFp.getTemplatesByPresetName(presetName, options).then((request) => request(axios, basePath));
        },
        /**
         * Update an existing menu template
         * @summary Update existing template
         * @param {number} id 
         * @param {MenuTemplateUpdateRequest} menuTemplateUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTemplate(id: number, menuTemplateUpdateRequest: MenuTemplateUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<MenuTemplateDTO> {
            return localVarFp.updateTemplate(id, menuTemplateUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminMenuTemplatesApi - interface
 * @export
 * @interface AdminMenuTemplatesApi
 */
export interface AdminMenuTemplatesApiInterface {
    /**
     * Create a new menu template
     * @summary Create new template
     * @param {MenuTemplateCreateRequest} menuTemplateCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuTemplatesApiInterface
     */
    createTemplate(menuTemplateCreateRequest: MenuTemplateCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<MenuTemplateDTO>;

    /**
     * Delete a menu template by ID
     * @summary Delete template
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuTemplatesApiInterface
     */
    deleteTemplate(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Delete all templates for a specific preset name
     * @summary Batch delete templates by preset
     * @param {string} presetName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuTemplatesApiInterface
     */
    deleteTemplatesByPresetName(presetName: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Retrieve all distinct preset names with metadata
     * @summary Get distinct preset names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuTemplatesApiInterface
     */
    getDistinctPresetNames(options?: RawAxiosRequestConfig): AxiosPromise<Array<PresetNameDTO>>;

    /**
     * Retrieve all templates for a specific preset name
     * @summary Get templates by preset name
     * @param {string} presetName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuTemplatesApiInterface
     */
    getTemplatesByPresetName(presetName: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuTemplateDTO>>;

    /**
     * Update an existing menu template
     * @summary Update existing template
     * @param {number} id 
     * @param {MenuTemplateUpdateRequest} menuTemplateUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuTemplatesApiInterface
     */
    updateTemplate(id: number, menuTemplateUpdateRequest: MenuTemplateUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<MenuTemplateDTO>;

}

/**
 * AdminMenuTemplatesApi - object-oriented interface
 * @export
 * @class AdminMenuTemplatesApi
 * @extends {BaseAPI}
 */
export class AdminMenuTemplatesApi extends BaseAPI implements AdminMenuTemplatesApiInterface {
    /**
     * Create a new menu template
     * @summary Create new template
     * @param {MenuTemplateCreateRequest} menuTemplateCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuTemplatesApi
     */
    public createTemplate(menuTemplateCreateRequest: MenuTemplateCreateRequest, options?: RawAxiosRequestConfig) {
        return AdminMenuTemplatesApiFp(this.configuration).createTemplate(menuTemplateCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a menu template by ID
     * @summary Delete template
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuTemplatesApi
     */
    public deleteTemplate(id: number, options?: RawAxiosRequestConfig) {
        return AdminMenuTemplatesApiFp(this.configuration).deleteTemplate(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete all templates for a specific preset name
     * @summary Batch delete templates by preset
     * @param {string} presetName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuTemplatesApi
     */
    public deleteTemplatesByPresetName(presetName: string, options?: RawAxiosRequestConfig) {
        return AdminMenuTemplatesApiFp(this.configuration).deleteTemplatesByPresetName(presetName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve all distinct preset names with metadata
     * @summary Get distinct preset names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuTemplatesApi
     */
    public getDistinctPresetNames(options?: RawAxiosRequestConfig) {
        return AdminMenuTemplatesApiFp(this.configuration).getDistinctPresetNames(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve all templates for a specific preset name
     * @summary Get templates by preset name
     * @param {string} presetName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuTemplatesApi
     */
    public getTemplatesByPresetName(presetName: string, options?: RawAxiosRequestConfig) {
        return AdminMenuTemplatesApiFp(this.configuration).getTemplatesByPresetName(presetName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update an existing menu template
     * @summary Update existing template
     * @param {number} id 
     * @param {MenuTemplateUpdateRequest} menuTemplateUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuTemplatesApi
     */
    public updateTemplate(id: number, menuTemplateUpdateRequest: MenuTemplateUpdateRequest, options?: RawAxiosRequestConfig) {
        return AdminMenuTemplatesApiFp(this.configuration).updateTemplate(id, menuTemplateUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

