/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AdminMenuItemCreateRequest } from '../models';
// @ts-ignore
import type { AdminMenuItemUpdateRequest } from '../models';
// @ts-ignore
import type { MenuItemDTO } from '../models';
// @ts-ignore
import type { MenuItemQueueRequest } from '../models';
// @ts-ignore
import type { MenuItemStatisticsDTO } from '../models';
/**
 * AdminMenuApi - axios parameter creator
 * @export
 */
export const AdminMenuApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a new menu item
         * @summary Create menu item
         * @param {AdminMenuItemCreateRequest} adminMenuItemCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMenuItem: async (adminMenuItemCreateRequest: AdminMenuItemCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'adminMenuItemCreateRequest' is not null or undefined
            assertParamExists('createMenuItem', 'adminMenuItemCreateRequest', adminMenuItemCreateRequest)
            const localVarPath = `/api/admin/menu`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adminMenuItemCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a menu item by ID. Only draft and current (non-historic) items can be deleted.
         * @summary Delete menu item
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMenuItem: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteMenuItem', 'id', id)
            const localVarPath = `/api/admin/menu/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve all released items with delivery, release, edit, and order dates where orderBy is not past
         * @summary Get current menu items
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentMenuItems: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/menu/current`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve all menu items with null delivery, release, edit and order dates
         * @summary Get draft menu items
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraftMenuItems: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/menu/items`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve all items where orderBy date is in the past
         * @summary Get historic menu items
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistoricMenuItems: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/menu/historic`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get statistics about popular items from order history
         * @summary Get menu item statistics
         * @param {string} [startDate] 
         * @param {string} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMenuItemStatistics: async (startDate?: string, endDate?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/menu/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString() :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString() :
                    endDate;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve menu items with pagination. Use /menu/items, /menu/current, or /menu/historic instead.
         * @summary Get paginated menu items (DEPRECATED)
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        getMenuPaginated: async (page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/menu`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new menu item by copying an existing one with new dates
         * @summary Queue a menu item
         * @param {MenuItemQueueRequest} menuItemQueueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queueMenuItem: async (menuItemQueueRequest: MenuItemQueueRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'menuItemQueueRequest' is not null or undefined
            assertParamExists('queueMenuItem', 'menuItemQueueRequest', menuItemQueueRequest)
            const localVarPath = `/api/admin/menu/queue`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(menuItemQueueRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search menu items with pagination
         * @summary Search menu items
         * @param {string} search 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchMenuPaginated: async (search: string, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'search' is not null or undefined
            assertParamExists('searchMenuPaginated', 'search', search)
            const localVarPath = `/api/admin/menu/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update an existing menu item
         * @summary Update menu item
         * @param {number} id 
         * @param {AdminMenuItemUpdateRequest} adminMenuItemUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMenuItem: async (id: number, adminMenuItemUpdateRequest: AdminMenuItemUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateMenuItem', 'id', id)
            // verify required parameter 'adminMenuItemUpdateRequest' is not null or undefined
            assertParamExists('updateMenuItem', 'adminMenuItemUpdateRequest', adminMenuItemUpdateRequest)
            const localVarPath = `/api/admin/menu/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adminMenuItemUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminMenuApi - functional programming interface
 * @export
 */
export const AdminMenuApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminMenuApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a new menu item
         * @summary Create menu item
         * @param {AdminMenuItemCreateRequest} adminMenuItemCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMenuItem(adminMenuItemCreateRequest: AdminMenuItemCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MenuItemDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createMenuItem(adminMenuItemCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuApi.createMenuItem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a menu item by ID. Only draft and current (non-historic) items can be deleted.
         * @summary Delete menu item
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMenuItem(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMenuItem(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuApi.deleteMenuItem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve all released items with delivery, release, edit, and order dates where orderBy is not past
         * @summary Get current menu items
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentMenuItems(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MenuItemDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentMenuItems(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuApi.getCurrentMenuItems']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve all menu items with null delivery, release, edit and order dates
         * @summary Get draft menu items
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDraftMenuItems(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MenuItemDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDraftMenuItems(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuApi.getDraftMenuItems']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve all items where orderBy date is in the past
         * @summary Get historic menu items
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHistoricMenuItems(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MenuItemDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHistoricMenuItems(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuApi.getHistoricMenuItems']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get statistics about popular items from order history
         * @summary Get menu item statistics
         * @param {string} [startDate] 
         * @param {string} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMenuItemStatistics(startDate?: string, endDate?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MenuItemStatisticsDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMenuItemStatistics(startDate, endDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuApi.getMenuItemStatistics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve menu items with pagination. Use /menu/items, /menu/current, or /menu/historic instead.
         * @summary Get paginated menu items (DEPRECATED)
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        async getMenuPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MenuItemDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMenuPaginated(page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuApi.getMenuPaginated']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new menu item by copying an existing one with new dates
         * @summary Queue a menu item
         * @param {MenuItemQueueRequest} menuItemQueueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async queueMenuItem(menuItemQueueRequest: MenuItemQueueRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MenuItemDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.queueMenuItem(menuItemQueueRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuApi.queueMenuItem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Search menu items with pagination
         * @summary Search menu items
         * @param {string} search 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchMenuPaginated(search: string, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MenuItemDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchMenuPaginated(search, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuApi.searchMenuPaginated']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update an existing menu item
         * @summary Update menu item
         * @param {number} id 
         * @param {AdminMenuItemUpdateRequest} adminMenuItemUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMenuItem(id: number, adminMenuItemUpdateRequest: AdminMenuItemUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MenuItemDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateMenuItem(id, adminMenuItemUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMenuApi.updateMenuItem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminMenuApi - factory interface
 * @export
 */
export const AdminMenuApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminMenuApiFp(configuration)
    return {
        /**
         * Create a new menu item
         * @summary Create menu item
         * @param {AdminMenuItemCreateRequest} adminMenuItemCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMenuItem(adminMenuItemCreateRequest: AdminMenuItemCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<MenuItemDTO> {
            return localVarFp.createMenuItem(adminMenuItemCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a menu item by ID. Only draft and current (non-historic) items can be deleted.
         * @summary Delete menu item
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMenuItem(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteMenuItem(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve all released items with delivery, release, edit, and order dates where orderBy is not past
         * @summary Get current menu items
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentMenuItems(options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemDTO>> {
            return localVarFp.getCurrentMenuItems(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve all menu items with null delivery, release, edit and order dates
         * @summary Get draft menu items
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraftMenuItems(options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemDTO>> {
            return localVarFp.getDraftMenuItems(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve all items where orderBy date is in the past
         * @summary Get historic menu items
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistoricMenuItems(options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemDTO>> {
            return localVarFp.getHistoricMenuItems(options).then((request) => request(axios, basePath));
        },
        /**
         * Get statistics about popular items from order history
         * @summary Get menu item statistics
         * @param {string} [startDate] 
         * @param {string} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMenuItemStatistics(startDate?: string, endDate?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemStatisticsDTO>> {
            return localVarFp.getMenuItemStatistics(startDate, endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve menu items with pagination. Use /menu/items, /menu/current, or /menu/historic instead.
         * @summary Get paginated menu items (DEPRECATED)
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        getMenuPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemDTO>> {
            return localVarFp.getMenuPaginated(page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new menu item by copying an existing one with new dates
         * @summary Queue a menu item
         * @param {MenuItemQueueRequest} menuItemQueueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queueMenuItem(menuItemQueueRequest: MenuItemQueueRequest, options?: RawAxiosRequestConfig): AxiosPromise<MenuItemDTO> {
            return localVarFp.queueMenuItem(menuItemQueueRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Search menu items with pagination
         * @summary Search menu items
         * @param {string} search 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchMenuPaginated(search: string, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemDTO>> {
            return localVarFp.searchMenuPaginated(search, page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * Update an existing menu item
         * @summary Update menu item
         * @param {number} id 
         * @param {AdminMenuItemUpdateRequest} adminMenuItemUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMenuItem(id: number, adminMenuItemUpdateRequest: AdminMenuItemUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<MenuItemDTO> {
            return localVarFp.updateMenuItem(id, adminMenuItemUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminMenuApi - interface
 * @export
 * @interface AdminMenuApi
 */
export interface AdminMenuApiInterface {
    /**
     * Create a new menu item
     * @summary Create menu item
     * @param {AdminMenuItemCreateRequest} adminMenuItemCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApiInterface
     */
    createMenuItem(adminMenuItemCreateRequest: AdminMenuItemCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<MenuItemDTO>;

    /**
     * Delete a menu item by ID. Only draft and current (non-historic) items can be deleted.
     * @summary Delete menu item
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApiInterface
     */
    deleteMenuItem(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Retrieve all released items with delivery, release, edit, and order dates where orderBy is not past
     * @summary Get current menu items
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApiInterface
     */
    getCurrentMenuItems(options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemDTO>>;

    /**
     * Retrieve all menu items with null delivery, release, edit and order dates
     * @summary Get draft menu items
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApiInterface
     */
    getDraftMenuItems(options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemDTO>>;

    /**
     * Retrieve all items where orderBy date is in the past
     * @summary Get historic menu items
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApiInterface
     */
    getHistoricMenuItems(options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemDTO>>;

    /**
     * Get statistics about popular items from order history
     * @summary Get menu item statistics
     * @param {string} [startDate] 
     * @param {string} [endDate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApiInterface
     */
    getMenuItemStatistics(startDate?: string, endDate?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemStatisticsDTO>>;

    /**
     * Retrieve menu items with pagination. Use /menu/items, /menu/current, or /menu/historic instead.
     * @summary Get paginated menu items (DEPRECATED)
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof AdminMenuApiInterface
     */
    getMenuPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemDTO>>;

    /**
     * Create a new menu item by copying an existing one with new dates
     * @summary Queue a menu item
     * @param {MenuItemQueueRequest} menuItemQueueRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApiInterface
     */
    queueMenuItem(menuItemQueueRequest: MenuItemQueueRequest, options?: RawAxiosRequestConfig): AxiosPromise<MenuItemDTO>;

    /**
     * Search menu items with pagination
     * @summary Search menu items
     * @param {string} search 
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApiInterface
     */
    searchMenuPaginated(search: string, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemDTO>>;

    /**
     * Update an existing menu item
     * @summary Update menu item
     * @param {number} id 
     * @param {AdminMenuItemUpdateRequest} adminMenuItemUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApiInterface
     */
    updateMenuItem(id: number, adminMenuItemUpdateRequest: AdminMenuItemUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<MenuItemDTO>;

}

/**
 * AdminMenuApi - object-oriented interface
 * @export
 * @class AdminMenuApi
 * @extends {BaseAPI}
 */
export class AdminMenuApi extends BaseAPI implements AdminMenuApiInterface {
    /**
     * Create a new menu item
     * @summary Create menu item
     * @param {AdminMenuItemCreateRequest} adminMenuItemCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApi
     */
    public createMenuItem(adminMenuItemCreateRequest: AdminMenuItemCreateRequest, options?: RawAxiosRequestConfig) {
        return AdminMenuApiFp(this.configuration).createMenuItem(adminMenuItemCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a menu item by ID. Only draft and current (non-historic) items can be deleted.
     * @summary Delete menu item
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApi
     */
    public deleteMenuItem(id: number, options?: RawAxiosRequestConfig) {
        return AdminMenuApiFp(this.configuration).deleteMenuItem(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve all released items with delivery, release, edit, and order dates where orderBy is not past
     * @summary Get current menu items
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApi
     */
    public getCurrentMenuItems(options?: RawAxiosRequestConfig) {
        return AdminMenuApiFp(this.configuration).getCurrentMenuItems(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve all menu items with null delivery, release, edit and order dates
     * @summary Get draft menu items
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApi
     */
    public getDraftMenuItems(options?: RawAxiosRequestConfig) {
        return AdminMenuApiFp(this.configuration).getDraftMenuItems(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve all items where orderBy date is in the past
     * @summary Get historic menu items
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApi
     */
    public getHistoricMenuItems(options?: RawAxiosRequestConfig) {
        return AdminMenuApiFp(this.configuration).getHistoricMenuItems(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get statistics about popular items from order history
     * @summary Get menu item statistics
     * @param {string} [startDate] 
     * @param {string} [endDate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApi
     */
    public getMenuItemStatistics(startDate?: string, endDate?: string, options?: RawAxiosRequestConfig) {
        return AdminMenuApiFp(this.configuration).getMenuItemStatistics(startDate, endDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve menu items with pagination. Use /menu/items, /menu/current, or /menu/historic instead.
     * @summary Get paginated menu items (DEPRECATED)
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof AdminMenuApi
     */
    public getMenuPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return AdminMenuApiFp(this.configuration).getMenuPaginated(page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new menu item by copying an existing one with new dates
     * @summary Queue a menu item
     * @param {MenuItemQueueRequest} menuItemQueueRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApi
     */
    public queueMenuItem(menuItemQueueRequest: MenuItemQueueRequest, options?: RawAxiosRequestConfig) {
        return AdminMenuApiFp(this.configuration).queueMenuItem(menuItemQueueRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Search menu items with pagination
     * @summary Search menu items
     * @param {string} search 
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApi
     */
    public searchMenuPaginated(search: string, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return AdminMenuApiFp(this.configuration).searchMenuPaginated(search, page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update an existing menu item
     * @summary Update menu item
     * @param {number} id 
     * @param {AdminMenuItemUpdateRequest} adminMenuItemUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMenuApi
     */
    public updateMenuItem(id: number, adminMenuItemUpdateRequest: AdminMenuItemUpdateRequest, options?: RawAxiosRequestConfig) {
        return AdminMenuApiFp(this.configuration).updateMenuItem(id, adminMenuItemUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

