/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PageTransactionAuditDTO } from '../models';
// @ts-ignore
import type { PageUserEventAuditDTO } from '../models';
// @ts-ignore
import type { TransactionWithUserDTO } from '../models';
// @ts-ignore
import type { UserEventAuditDTO } from '../models';
/**
 * AdminAuditApi - axios parameter creator
 * @export
 */
export const AdminAuditApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve recent user login events
         * @summary Get recent user logins
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecentLogins: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/audit/logins/recent`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve transaction audit records with pagination
         * @summary Get paginated transaction audit
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransactionAuditPaginated: async (page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/audit/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve detailed transaction information including account owner details for a specific audit record
         * @summary Get transaction details for audit
         * @param {number} auditId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransactionDetailsForAudit: async (auditId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'auditId' is not null or undefined
            assertParamExists('getTransactionDetailsForAudit', 'auditId', auditId)
            const localVarPath = `/api/admin/audit/transactions/{auditId}/details`
                .replace(`{${"auditId"}}`, encodeURIComponent(String(auditId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve user events with pagination
         * @summary Get paginated user events
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserEventLogPaginated: async (page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/audit/user-events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminAuditApi - functional programming interface
 * @export
 */
export const AdminAuditApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminAuditApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve recent user login events
         * @summary Get recent user logins
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRecentLogins(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserEventAuditDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRecentLogins(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAuditApi.getRecentLogins']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve transaction audit records with pagination
         * @summary Get paginated transaction audit
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTransactionAuditPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageTransactionAuditDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTransactionAuditPaginated(page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAuditApi.getTransactionAuditPaginated']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve detailed transaction information including account owner details for a specific audit record
         * @summary Get transaction details for audit
         * @param {number} auditId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTransactionDetailsForAudit(auditId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TransactionWithUserDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTransactionDetailsForAudit(auditId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAuditApi.getTransactionDetailsForAudit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve user events with pagination
         * @summary Get paginated user events
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserEventLogPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageUserEventAuditDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserEventLogPaginated(page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAuditApi.getUserEventLogPaginated']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminAuditApi - factory interface
 * @export
 */
export const AdminAuditApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminAuditApiFp(configuration)
    return {
        /**
         * Retrieve recent user login events
         * @summary Get recent user logins
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecentLogins(options?: RawAxiosRequestConfig): AxiosPromise<Array<UserEventAuditDTO>> {
            return localVarFp.getRecentLogins(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve transaction audit records with pagination
         * @summary Get paginated transaction audit
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransactionAuditPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<PageTransactionAuditDTO> {
            return localVarFp.getTransactionAuditPaginated(page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve detailed transaction information including account owner details for a specific audit record
         * @summary Get transaction details for audit
         * @param {number} auditId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransactionDetailsForAudit(auditId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<TransactionWithUserDTO>> {
            return localVarFp.getTransactionDetailsForAudit(auditId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve user events with pagination
         * @summary Get paginated user events
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserEventLogPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<PageUserEventAuditDTO> {
            return localVarFp.getUserEventLogPaginated(page, size, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminAuditApi - interface
 * @export
 * @interface AdminAuditApi
 */
export interface AdminAuditApiInterface {
    /**
     * Retrieve recent user login events
     * @summary Get recent user logins
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuditApiInterface
     */
    getRecentLogins(options?: RawAxiosRequestConfig): AxiosPromise<Array<UserEventAuditDTO>>;

    /**
     * Retrieve transaction audit records with pagination
     * @summary Get paginated transaction audit
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuditApiInterface
     */
    getTransactionAuditPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<PageTransactionAuditDTO>;

    /**
     * Retrieve detailed transaction information including account owner details for a specific audit record
     * @summary Get transaction details for audit
     * @param {number} auditId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuditApiInterface
     */
    getTransactionDetailsForAudit(auditId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<TransactionWithUserDTO>>;

    /**
     * Retrieve user events with pagination
     * @summary Get paginated user events
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuditApiInterface
     */
    getUserEventLogPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<PageUserEventAuditDTO>;

}

/**
 * AdminAuditApi - object-oriented interface
 * @export
 * @class AdminAuditApi
 * @extends {BaseAPI}
 */
export class AdminAuditApi extends BaseAPI implements AdminAuditApiInterface {
    /**
     * Retrieve recent user login events
     * @summary Get recent user logins
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuditApi
     */
    public getRecentLogins(options?: RawAxiosRequestConfig) {
        return AdminAuditApiFp(this.configuration).getRecentLogins(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve transaction audit records with pagination
     * @summary Get paginated transaction audit
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuditApi
     */
    public getTransactionAuditPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return AdminAuditApiFp(this.configuration).getTransactionAuditPaginated(page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve detailed transaction information including account owner details for a specific audit record
     * @summary Get transaction details for audit
     * @param {number} auditId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuditApi
     */
    public getTransactionDetailsForAudit(auditId: number, options?: RawAxiosRequestConfig) {
        return AdminAuditApiFp(this.configuration).getTransactionDetailsForAudit(auditId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve user events with pagination
     * @summary Get paginated user events
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuditApi
     */
    public getUserEventLogPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return AdminAuditApiFp(this.configuration).getUserEventLogPaginated(page, size, options).then((request) => request(this.axios, this.basePath));
    }
}

