/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AllergyEntity } from '../models';
/**
 * AdminAllergyManagementApi - axios parameter creator
 * @export
 */
export const AdminAllergyManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new resource
         * @param {AllergyEntity} allergyEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create2: async (allergyEntity: AllergyEntity, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'allergyEntity' is not null or undefined
            assertParamExists('create2', 'allergyEntity', allergyEntity)
            const localVarPath = `/api/admin/allergies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(allergyEntity, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a resource
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delete2: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('delete2', 'id', id)
            const localVarPath = `/api/admin/allergies/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find all resources
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findAll2: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/allergies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find a resource by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findById2: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('findById2', 'id', id)
            const localVarPath = `/api/admin/allergies/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a resource
         * @param {number} id 
         * @param {AllergyEntity} allergyEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update2: async (id: number, allergyEntity: AllergyEntity, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('update2', 'id', id)
            // verify required parameter 'allergyEntity' is not null or undefined
            assertParamExists('update2', 'allergyEntity', allergyEntity)
            const localVarPath = `/api/admin/allergies/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(allergyEntity, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminAllergyManagementApi - functional programming interface
 * @export
 */
export const AdminAllergyManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminAllergyManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new resource
         * @param {AllergyEntity} allergyEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create2(allergyEntity: AllergyEntity, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AllergyEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create2(allergyEntity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAllergyManagementApi.create2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a resource
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async delete2(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.delete2(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAllergyManagementApi.delete2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Find all resources
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findAll2(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AllergyEntity>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findAll2(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAllergyManagementApi.findAll2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Find a resource by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findById2(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AllergyEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findById2(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAllergyManagementApi.findById2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a resource
         * @param {number} id 
         * @param {AllergyEntity} allergyEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update2(id: number, allergyEntity: AllergyEntity, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AllergyEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update2(id, allergyEntity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAllergyManagementApi.update2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminAllergyManagementApi - factory interface
 * @export
 */
export const AdminAllergyManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminAllergyManagementApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new resource
         * @param {AllergyEntity} allergyEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create2(allergyEntity: AllergyEntity, options?: RawAxiosRequestConfig): AxiosPromise<AllergyEntity> {
            return localVarFp.create2(allergyEntity, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a resource
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delete2(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.delete2(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find all resources
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findAll2(options?: RawAxiosRequestConfig): AxiosPromise<Array<AllergyEntity>> {
            return localVarFp.findAll2(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find a resource by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findById2(id: number, options?: RawAxiosRequestConfig): AxiosPromise<AllergyEntity> {
            return localVarFp.findById2(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a resource
         * @param {number} id 
         * @param {AllergyEntity} allergyEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update2(id: number, allergyEntity: AllergyEntity, options?: RawAxiosRequestConfig): AxiosPromise<AllergyEntity> {
            return localVarFp.update2(id, allergyEntity, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminAllergyManagementApi - interface
 * @export
 * @interface AdminAllergyManagementApi
 */
export interface AdminAllergyManagementApiInterface {
    /**
     * 
     * @summary Create a new resource
     * @param {AllergyEntity} allergyEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAllergyManagementApiInterface
     */
    create2(allergyEntity: AllergyEntity, options?: RawAxiosRequestConfig): AxiosPromise<AllergyEntity>;

    /**
     * 
     * @summary Delete a resource
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAllergyManagementApiInterface
     */
    delete2(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Find all resources
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAllergyManagementApiInterface
     */
    findAll2(options?: RawAxiosRequestConfig): AxiosPromise<Array<AllergyEntity>>;

    /**
     * 
     * @summary Find a resource by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAllergyManagementApiInterface
     */
    findById2(id: number, options?: RawAxiosRequestConfig): AxiosPromise<AllergyEntity>;

    /**
     * 
     * @summary Update a resource
     * @param {number} id 
     * @param {AllergyEntity} allergyEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAllergyManagementApiInterface
     */
    update2(id: number, allergyEntity: AllergyEntity, options?: RawAxiosRequestConfig): AxiosPromise<AllergyEntity>;

}

/**
 * AdminAllergyManagementApi - object-oriented interface
 * @export
 * @class AdminAllergyManagementApi
 * @extends {BaseAPI}
 */
export class AdminAllergyManagementApi extends BaseAPI implements AdminAllergyManagementApiInterface {
    /**
     * 
     * @summary Create a new resource
     * @param {AllergyEntity} allergyEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAllergyManagementApi
     */
    public create2(allergyEntity: AllergyEntity, options?: RawAxiosRequestConfig) {
        return AdminAllergyManagementApiFp(this.configuration).create2(allergyEntity, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a resource
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAllergyManagementApi
     */
    public delete2(id: number, options?: RawAxiosRequestConfig) {
        return AdminAllergyManagementApiFp(this.configuration).delete2(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Find all resources
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAllergyManagementApi
     */
    public findAll2(options?: RawAxiosRequestConfig) {
        return AdminAllergyManagementApiFp(this.configuration).findAll2(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Find a resource by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAllergyManagementApi
     */
    public findById2(id: number, options?: RawAxiosRequestConfig) {
        return AdminAllergyManagementApiFp(this.configuration).findById2(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a resource
     * @param {number} id 
     * @param {AllergyEntity} allergyEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAllergyManagementApi
     */
    public update2(id: number, allergyEntity: AllergyEntity, options?: RawAxiosRequestConfig) {
        return AdminAllergyManagementApiFp(this.configuration).update2(id, allergyEntity, options).then((request) => request(this.axios, this.basePath));
    }
}

