/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SelectDTO } from '../models';
/**
 * ListApi - axios parameter creator
 * @export
 */
export const ListApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all allergy names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllergyNames: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/list/allergies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all campus names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCampusNames: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/list/campuses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all residence names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getResidenceNames: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/list/residences`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ListApi - functional programming interface
 * @export
 */
export const ListApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ListApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all allergy names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllergyNames(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SelectDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllergyNames(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListApi.getAllergyNames']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all campus names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCampusNames(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SelectDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCampusNames(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListApi.getCampusNames']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all residence names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getResidenceNames(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SelectDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getResidenceNames(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListApi.getResidenceNames']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ListApi - factory interface
 * @export
 */
export const ListApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ListApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all allergy names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllergyNames(options?: RawAxiosRequestConfig): AxiosPromise<Array<SelectDTO>> {
            return localVarFp.getAllergyNames(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all campus names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCampusNames(options?: RawAxiosRequestConfig): AxiosPromise<Array<SelectDTO>> {
            return localVarFp.getCampusNames(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all residence names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getResidenceNames(options?: RawAxiosRequestConfig): AxiosPromise<Array<SelectDTO>> {
            return localVarFp.getResidenceNames(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ListApi - interface
 * @export
 * @interface ListApi
 */
export interface ListApiInterface {
    /**
     * 
     * @summary Get all allergy names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListApiInterface
     */
    getAllergyNames(options?: RawAxiosRequestConfig): AxiosPromise<Array<SelectDTO>>;

    /**
     * 
     * @summary Get all campus names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListApiInterface
     */
    getCampusNames(options?: RawAxiosRequestConfig): AxiosPromise<Array<SelectDTO>>;

    /**
     * 
     * @summary Get all residence names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListApiInterface
     */
    getResidenceNames(options?: RawAxiosRequestConfig): AxiosPromise<Array<SelectDTO>>;

}

/**
 * ListApi - object-oriented interface
 * @export
 * @class ListApi
 * @extends {BaseAPI}
 */
export class ListApi extends BaseAPI implements ListApiInterface {
    /**
     * 
     * @summary Get all allergy names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListApi
     */
    public getAllergyNames(options?: RawAxiosRequestConfig) {
        return ListApiFp(this.configuration).getAllergyNames(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all campus names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListApi
     */
    public getCampusNames(options?: RawAxiosRequestConfig) {
        return ListApiFp(this.configuration).getCampusNames(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all residence names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListApi
     */
    public getResidenceNames(options?: RawAxiosRequestConfig) {
        return ListApiFp(this.configuration).getResidenceNames(options).then((request) => request(this.axios, this.basePath));
    }
}

