/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MenuItemDTO } from '../models';
/**
 * UserMenuApi - axios parameter creator
 * @export
 */
export const UserMenuApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve available menu items
         * @summary Get menu
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMenu: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/menu`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve detailed information about a menu item
         * @summary Get menu item detail
         * @param {number} itemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMenuItemDetail: async (itemId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'itemId' is not null or undefined
            assertParamExists('getMenuItemDetail', 'itemId', itemId)
            const localVarPath = `/api/user/menu/{itemId}`
                .replace(`{${"itemId"}}`, encodeURIComponent(String(itemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserMenuApi - functional programming interface
 * @export
 */
export const UserMenuApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserMenuApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve available menu items
         * @summary Get menu
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMenu(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MenuItemDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMenu(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserMenuApi.getMenu']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve detailed information about a menu item
         * @summary Get menu item detail
         * @param {number} itemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMenuItemDetail(itemId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MenuItemDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMenuItemDetail(itemId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserMenuApi.getMenuItemDetail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserMenuApi - factory interface
 * @export
 */
export const UserMenuApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserMenuApiFp(configuration)
    return {
        /**
         * Retrieve available menu items
         * @summary Get menu
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMenu(options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemDTO>> {
            return localVarFp.getMenu(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve detailed information about a menu item
         * @summary Get menu item detail
         * @param {number} itemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMenuItemDetail(itemId: number, options?: RawAxiosRequestConfig): AxiosPromise<MenuItemDTO> {
            return localVarFp.getMenuItemDetail(itemId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserMenuApi - interface
 * @export
 * @interface UserMenuApi
 */
export interface UserMenuApiInterface {
    /**
     * Retrieve available menu items
     * @summary Get menu
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserMenuApiInterface
     */
    getMenu(options?: RawAxiosRequestConfig): AxiosPromise<Array<MenuItemDTO>>;

    /**
     * Retrieve detailed information about a menu item
     * @summary Get menu item detail
     * @param {number} itemId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserMenuApiInterface
     */
    getMenuItemDetail(itemId: number, options?: RawAxiosRequestConfig): AxiosPromise<MenuItemDTO>;

}

/**
 * UserMenuApi - object-oriented interface
 * @export
 * @class UserMenuApi
 * @extends {BaseAPI}
 */
export class UserMenuApi extends BaseAPI implements UserMenuApiInterface {
    /**
     * Retrieve available menu items
     * @summary Get menu
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserMenuApi
     */
    public getMenu(options?: RawAxiosRequestConfig) {
        return UserMenuApiFp(this.configuration).getMenu(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve detailed information about a menu item
     * @summary Get menu item detail
     * @param {number} itemId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserMenuApi
     */
    public getMenuItemDetail(itemId: number, options?: RawAxiosRequestConfig) {
        return UserMenuApiFp(this.configuration).getMenuItemDetail(itemId, options).then((request) => request(this.axios, this.basePath));
    }
}

