/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { OrderDTO } from '../models';
// @ts-ignore
import type { OrderItemDTO } from '../models';
// @ts-ignore
import type { PlaceOrderRequest } from '../models';
/**
 * UserOrdersApi - axios parameter creator
 * @export
 */
export const UserOrdersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Cancel a specific order item for the current user
         * @summary Cancel an order item
         * @param {number} orderItemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelOrderItem: async (orderItemId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderItemId' is not null or undefined
            assertParamExists('cancelOrderItem', 'orderItemId', orderItemId)
            const localVarPath = `/api/user/orders/{orderItemId}/cancel`
                .replace(`{${"orderItemId"}}`, encodeURIComponent(String(orderItemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new order for the current user
         * @summary Create a new order
         * @param {PlaceOrderRequest} placeOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrder: async (placeOrderRequest: PlaceOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'placeOrderRequest' is not null or undefined
            assertParamExists('createOrder', 'placeOrderRequest', placeOrderRequest)
            const localVarPath = `/api/user/orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(placeOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve historic user orders
         * @summary Get user order history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserOrderHistory: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/orders/historic`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve all pending order items for current user
         * @summary Get user order item schedule
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserOrders: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/orders/schedule`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserOrdersApi - functional programming interface
 * @export
 */
export const UserOrdersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserOrdersApiAxiosParamCreator(configuration)
    return {
        /**
         * Cancel a specific order item for the current user
         * @summary Cancel an order item
         * @param {number} orderItemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelOrderItem(orderItemId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelOrderItem(orderItemId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserOrdersApi.cancelOrderItem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new order for the current user
         * @summary Create a new order
         * @param {PlaceOrderRequest} placeOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrder(placeOrderRequest: PlaceOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrderDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrder(placeOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserOrdersApi.createOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve historic user orders
         * @summary Get user order history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserOrderHistory(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<OrderItemDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserOrderHistory(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserOrdersApi.getUserOrderHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve all pending order items for current user
         * @summary Get user order item schedule
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserOrders(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<OrderItemDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserOrders(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserOrdersApi.getUserOrders']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserOrdersApi - factory interface
 * @export
 */
export const UserOrdersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserOrdersApiFp(configuration)
    return {
        /**
         * Cancel a specific order item for the current user
         * @summary Cancel an order item
         * @param {number} orderItemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelOrderItem(orderItemId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cancelOrderItem(orderItemId, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new order for the current user
         * @summary Create a new order
         * @param {PlaceOrderRequest} placeOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrder(placeOrderRequest: PlaceOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<OrderDTO> {
            return localVarFp.createOrder(placeOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve historic user orders
         * @summary Get user order history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserOrderHistory(options?: RawAxiosRequestConfig): AxiosPromise<Array<OrderItemDTO>> {
            return localVarFp.getUserOrderHistory(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve all pending order items for current user
         * @summary Get user order item schedule
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserOrders(options?: RawAxiosRequestConfig): AxiosPromise<Array<OrderItemDTO>> {
            return localVarFp.getUserOrders(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserOrdersApi - interface
 * @export
 * @interface UserOrdersApi
 */
export interface UserOrdersApiInterface {
    /**
     * Cancel a specific order item for the current user
     * @summary Cancel an order item
     * @param {number} orderItemId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserOrdersApiInterface
     */
    cancelOrderItem(orderItemId: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Create a new order for the current user
     * @summary Create a new order
     * @param {PlaceOrderRequest} placeOrderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserOrdersApiInterface
     */
    createOrder(placeOrderRequest: PlaceOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<OrderDTO>;

    /**
     * Retrieve historic user orders
     * @summary Get user order history
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserOrdersApiInterface
     */
    getUserOrderHistory(options?: RawAxiosRequestConfig): AxiosPromise<Array<OrderItemDTO>>;

    /**
     * Retrieve all pending order items for current user
     * @summary Get user order item schedule
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserOrdersApiInterface
     */
    getUserOrders(options?: RawAxiosRequestConfig): AxiosPromise<Array<OrderItemDTO>>;

}

/**
 * UserOrdersApi - object-oriented interface
 * @export
 * @class UserOrdersApi
 * @extends {BaseAPI}
 */
export class UserOrdersApi extends BaseAPI implements UserOrdersApiInterface {
    /**
     * Cancel a specific order item for the current user
     * @summary Cancel an order item
     * @param {number} orderItemId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserOrdersApi
     */
    public cancelOrderItem(orderItemId: number, options?: RawAxiosRequestConfig) {
        return UserOrdersApiFp(this.configuration).cancelOrderItem(orderItemId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new order for the current user
     * @summary Create a new order
     * @param {PlaceOrderRequest} placeOrderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserOrdersApi
     */
    public createOrder(placeOrderRequest: PlaceOrderRequest, options?: RawAxiosRequestConfig) {
        return UserOrdersApiFp(this.configuration).createOrder(placeOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve historic user orders
     * @summary Get user order history
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserOrdersApi
     */
    public getUserOrderHistory(options?: RawAxiosRequestConfig) {
        return UserOrdersApiFp(this.configuration).getUserOrderHistory(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve all pending order items for current user
     * @summary Get user order item schedule
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserOrdersApi
     */
    public getUserOrders(options?: RawAxiosRequestConfig) {
        return UserOrdersApiFp(this.configuration).getUserOrders(options).then((request) => request(this.axios, this.basePath));
    }
}

