/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { FeedbackDTO } from '../models';
// @ts-ignore
import type { FeedbackRequest } from '../models';
/**
 * UserFeedbackApi - axios parameter creator
 * @export
 */
export const UserFeedbackApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Submit feedback for a menu item in an order
         * @summary Submit feedback
         * @param {FeedbackRequest} feedbackRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        placeFeedback: async (feedbackRequest: FeedbackRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'feedbackRequest' is not null or undefined
            assertParamExists('placeFeedback', 'feedbackRequest', feedbackRequest)
            const localVarPath = `/api/user/feedback`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(feedbackRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserFeedbackApi - functional programming interface
 * @export
 */
export const UserFeedbackApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserFeedbackApiAxiosParamCreator(configuration)
    return {
        /**
         * Submit feedback for a menu item in an order
         * @summary Submit feedback
         * @param {FeedbackRequest} feedbackRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async placeFeedback(feedbackRequest: FeedbackRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FeedbackDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.placeFeedback(feedbackRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserFeedbackApi.placeFeedback']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserFeedbackApi - factory interface
 * @export
 */
export const UserFeedbackApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserFeedbackApiFp(configuration)
    return {
        /**
         * Submit feedback for a menu item in an order
         * @summary Submit feedback
         * @param {FeedbackRequest} feedbackRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        placeFeedback(feedbackRequest: FeedbackRequest, options?: RawAxiosRequestConfig): AxiosPromise<FeedbackDTO> {
            return localVarFp.placeFeedback(feedbackRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserFeedbackApi - interface
 * @export
 * @interface UserFeedbackApi
 */
export interface UserFeedbackApiInterface {
    /**
     * Submit feedback for a menu item in an order
     * @summary Submit feedback
     * @param {FeedbackRequest} feedbackRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserFeedbackApiInterface
     */
    placeFeedback(feedbackRequest: FeedbackRequest, options?: RawAxiosRequestConfig): AxiosPromise<FeedbackDTO>;

}

/**
 * UserFeedbackApi - object-oriented interface
 * @export
 * @class UserFeedbackApi
 * @extends {BaseAPI}
 */
export class UserFeedbackApi extends BaseAPI implements UserFeedbackApiInterface {
    /**
     * Submit feedback for a menu item in an order
     * @summary Submit feedback
     * @param {FeedbackRequest} feedbackRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserFeedbackApi
     */
    public placeFeedback(feedbackRequest: FeedbackRequest, options?: RawAxiosRequestConfig) {
        return UserFeedbackApiFp(this.configuration).placeFeedback(feedbackRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

