/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AccountDTO } from '../models';
// @ts-ignore
import type { TransactionDTO } from '../models';
/**
 * UserAccountApi - axios parameter creator
 * @export
 */
export const UserAccountApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve current user\'s account information
         * @summary Get account details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccount: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/account`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve transactions with pagination
         * @summary Get paginated transactions
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransactionsPaginated: async (page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer Authentication required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserAccountApi - functional programming interface
 * @export
 */
export const UserAccountApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserAccountApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve current user\'s account information
         * @summary Get account details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAccount(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAccount(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserAccountApi.getAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve transactions with pagination
         * @summary Get paginated transactions
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTransactionsPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TransactionDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTransactionsPaginated(page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserAccountApi.getTransactionsPaginated']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserAccountApi - factory interface
 * @export
 */
export const UserAccountApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserAccountApiFp(configuration)
    return {
        /**
         * Retrieve current user\'s account information
         * @summary Get account details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccount(options?: RawAxiosRequestConfig): AxiosPromise<AccountDTO> {
            return localVarFp.getAccount(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve transactions with pagination
         * @summary Get paginated transactions
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransactionsPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<TransactionDTO>> {
            return localVarFp.getTransactionsPaginated(page, size, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserAccountApi - interface
 * @export
 * @interface UserAccountApi
 */
export interface UserAccountApiInterface {
    /**
     * Retrieve current user\'s account information
     * @summary Get account details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountApiInterface
     */
    getAccount(options?: RawAxiosRequestConfig): AxiosPromise<AccountDTO>;

    /**
     * Retrieve transactions with pagination
     * @summary Get paginated transactions
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountApiInterface
     */
    getTransactionsPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<TransactionDTO>>;

}

/**
 * UserAccountApi - object-oriented interface
 * @export
 * @class UserAccountApi
 * @extends {BaseAPI}
 */
export class UserAccountApi extends BaseAPI implements UserAccountApiInterface {
    /**
     * Retrieve current user\'s account information
     * @summary Get account details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountApi
     */
    public getAccount(options?: RawAxiosRequestConfig) {
        return UserAccountApiFp(this.configuration).getAccount(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve transactions with pagination
     * @summary Get paginated transactions
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountApi
     */
    public getTransactionsPaginated(page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return UserAccountApiFp(this.configuration).getTransactionsPaginated(page, size, options).then((request) => request(this.axios, this.basePath));
    }
}

