/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdminOrderStatisticLine
 */
export interface AdminOrderStatisticLine {
    /**
     * 
     * @type {string}
     * @memberof AdminOrderStatisticLine
     */
    'itemName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOrderStatisticLine
     */
    'itemStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOrderStatisticLine
     */
    'deliveryDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof AdminOrderStatisticLine
     */
    'itemCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminOrderStatisticLine
     */
    'totalRevenue'?: number;
}

