/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserWithProfileDTO } from './user-with-profile-dto';

/**
 * 
 * @export
 * @interface AdminTransactionDTO
 */
export interface AdminTransactionDTO {
    /**
     * 
     * @type {number}
     * @memberof AdminTransactionDTO
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminTransactionDTO
     */
    'debit'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminTransactionDTO
     */
    'credit'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminTransactionDTO
     */
    'runningBalance'?: number;
    /**
     * 
     * @type {string}
     * @memberof AdminTransactionDTO
     */
    'transactionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminTransactionDTO
     */
    'description'?: string;
    /**
     * 
     * @type {UserWithProfileDTO}
     * @memberof AdminTransactionDTO
     */
    'user'?: UserWithProfileDTO;
}

