/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdminLoadCreditResult } from './admin-load-credit-result';
// May contain unused imports in some cases
// @ts-ignore
import type { CompactUserDTO } from './compact-user-dto';

/**
 * 
 * @export
 * @interface AdminFinanceLoadResponse
 */
export interface AdminFinanceLoadResponse {
    /**
     * 
     * @type {number}
     * @memberof AdminFinanceLoadResponse
     */
    'auditId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminFinanceLoadResponse
     */
    'totalRequests'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminFinanceLoadResponse
     */
    'successfulLoads'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminFinanceLoadResponse
     */
    'failedLoads'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminFinanceLoadResponse
     */
    'totalAmountLoaded'?: number;
    /**
     * 
     * @type {Array<AdminLoadCreditResult>}
     * @memberof AdminFinanceLoadResponse
     */
    'results'?: Array<AdminLoadCreditResult>;
    /**
     * 
     * @type {string}
     * @memberof AdminFinanceLoadResponse
     */
    'processedAt'?: string;
    /**
     * 
     * @type {CompactUserDTO}
     * @memberof AdminFinanceLoadResponse
     */
    'processedBy'?: CompactUserDTO;
}

