/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Delivery statistics for the dashboard
 * @export
 * @interface DeliveryStatisticsResponse
 */
export interface DeliveryStatisticsResponse {
    /**
     * Total items to deliver today
     * @type {number}
     * @memberof DeliveryStatisticsResponse
     */
    'totalItemsToday'?: number;
    /**
     * Items currently in delivery status
     * @type {number}
     * @memberof DeliveryStatisticsResponse
     */
    'itemsInDelivery'?: number;
    /**
     * Items successfully delivered today
     * @type {number}
     * @memberof DeliveryStatisticsResponse
     */
    'itemsDelivered'?: number;
    /**
     * Completion percentage
     * @type {number}
     * @memberof DeliveryStatisticsResponse
     */
    'completionPercentage'?: number;
}

