/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeliveryReportItem } from './delivery-report-item';

/**
 * 
 * @export
 * @interface DeliveryReportData
 */
export interface DeliveryReportData {
    /**
     * 
     * @type {string}
     * @memberof DeliveryReportData
     */
    'startDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryReportData
     */
    'endDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryReportData
     */
    'generatedAt'?: string;
    /**
     * 
     * @type {Array<DeliveryReportItem>}
     * @memberof DeliveryReportData
     */
    'deliveries'?: Array<DeliveryReportItem>;
    /**
     * 
     * @type {number}
     * @memberof DeliveryReportData
     */
    'totalDeliveries'?: number;
    /**
     * 
     * @type {number}
     * @memberof DeliveryReportData
     */
    'uniqueCampuses'?: number;
    /**
     * 
     * @type {number}
     * @memberof DeliveryReportData
     */
    'uniqueResidences'?: number;
}

