/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderItemDTO } from './order-item-dto';

/**
 * Response after marking an item as delivered
 * @export
 * @interface DeliveryConfirmationResponse
 */
export interface DeliveryConfirmationResponse {
    /**
     * The delivered order item
     * @type {OrderItemDTO}
     * @memberof DeliveryConfirmationResponse
     */
    'deliveredItem'?: OrderItemDTO;
    /**
     * Success message
     * @type {string}
     * @memberof DeliveryConfirmationResponse
     */
    'message'?: string;
    /**
     * Number of remaining items for this user
     * @type {number}
     * @memberof DeliveryConfirmationResponse
     */
    'remainingItems'?: number;
}

