/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FeedbackRequest
 */
export interface FeedbackRequest {
    /**
     * 
     * @type {number}
     * @memberof FeedbackRequest
     */
    'menuItemId'?: number;
    /**
     * 
     * @type {number}
     * @memberof FeedbackRequest
     */
    'rating': number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackRequest
     */
    'comment'?: string;
}

