/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MenuItemQueueRequest
 */
export interface MenuItemQueueRequest {
    /**
     * 
     * @type {number}
     * @memberof MenuItemQueueRequest
     */
    'sourceMenuItemId': number;
    /**
     * 
     * @type {string}
     * @memberof MenuItemQueueRequest
     */
    'deliveryDate': string;
    /**
     * 
     * @type {string}
     * @memberof MenuItemQueueRequest
     */
    'releaseDate': string;
    /**
     * 
     * @type {string}
     * @memberof MenuItemQueueRequest
     */
    'editBy': string;
    /**
     * 
     * @type {string}
     * @memberof MenuItemQueueRequest
     */
    'orderBy': string;
}

