/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MenuTemplateUpdateRequest
 */
export interface MenuTemplateUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof MenuTemplateUpdateRequest
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof MenuTemplateUpdateRequest
     */
    'deliveryOffsetMinutes'?: number;
    /**
     * 
     * @type {number}
     * @memberof MenuTemplateUpdateRequest
     */
    'releaseOffsetMinutes'?: number;
    /**
     * 
     * @type {number}
     * @memberof MenuTemplateUpdateRequest
     */
    'orderByOffsetMinutes'?: number;
    /**
     * 
     * @type {string}
     * @memberof MenuTemplateUpdateRequest
     */
    'presetName'?: string;
}

