/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MenuItemStatisticsDTO
 */
export interface MenuItemStatisticsDTO {
    /**
     * 
     * @type {number}
     * @memberof MenuItemStatisticsDTO
     */
    'menuItemId'?: number;
    /**
     * 
     * @type {string}
     * @memberof MenuItemStatisticsDTO
     */
    'menuItemName'?: string;
    /**
     * 
     * @type {number}
     * @memberof MenuItemStatisticsDTO
     */
    'totalOrders'?: number;
    /**
     * 
     * @type {number}
     * @memberof MenuItemStatisticsDTO
     */
    'totalQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof MenuItemStatisticsDTO
     */
    'totalRevenue'?: number;
}

