/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NotificationDTO
 */
export interface NotificationDTO {
    /**
     * 
     * @type {number}
     * @memberof NotificationDTO
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'type'?: TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'status'?: StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'deepLinkUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'imageUrl'?: string;
    /**
     * 
     * @type {number}
     * @memberof NotificationDTO
     */
    'relatedOrderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'scheduledFor'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'sentAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'deliveredAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'readAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'expiresAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationDTO
     */
    'expired'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationDTO
     */
    'readyToSend'?: boolean;
}

export const TypeEnum = {
    ORDER_CONFIRMATION: 'ORDER_CONFIRMATION',
    ORDER_READY: 'ORDER_READY',
    ORDER_CANCELLED: 'ORDER_CANCELLED',
    MENU_UPDATE: 'MENU_UPDATE',
    ACCOUNT_BALANCE_LOW: 'ACCOUNT_BALANCE_LOW',
    ACCOUNT_CREDITED: 'ACCOUNT_CREDITED',
    SYSTEM_MAINTENANCE: 'SYSTEM_MAINTENANCE',
    PROMOTIONAL: 'PROMOTIONAL',
    GENERAL_ANNOUNCEMENT: 'GENERAL_ANNOUNCEMENT'
} as const;

export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
export const StatusEnum = {
    PENDING: 'PENDING',
    SENT: 'SENT',
    DELIVERED: 'DELIVERED',
    READ: 'READ',
    FAILED: 'FAILED'
} as const;

export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];


