/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NotificationRequest
 */
export interface NotificationRequest {
    /**
     * 
     * @type {string}
     * @memberof NotificationRequest
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationRequest
     */
    'body'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationRequest
     */
    'icon'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationRequest
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationRequest
     */
    'type'?: TypeEnum;
}

export const TypeEnum = {
    ORDER_CONFIRMATION: 'ORDER_CONFIRMATION',
    ORDER_READY: 'ORDER_READY',
    ORDER_CANCELLED: 'ORDER_CANCELLED',
    MENU_UPDATE: 'MENU_UPDATE',
    ACCOUNT_BALANCE_LOW: 'ACCOUNT_BALANCE_LOW',
    ACCOUNT_CREDITED: 'ACCOUNT_CREDITED',
    SYSTEM_MAINTENANCE: 'SYSTEM_MAINTENANCE',
    PROMOTIONAL: 'PROMOTIONAL',
    GENERAL_ANNOUNCEMENT: 'GENERAL_ANNOUNCEMENT'
} as const;

export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];


