/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderItemRequest } from './order-item-request';

/**
 * 
 * @export
 * @interface OrderEditRequest
 */
export interface OrderEditRequest {
    /**
     * 
     * @type {number}
     * @memberof OrderEditRequest
     */
    'orderId': number;
    /**
     * 
     * @type {Array<OrderItemRequest>}
     * @memberof OrderEditRequest
     */
    'items': Array<OrderItemRequest>;
}

