/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompactUserDTO } from './compact-user-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderItemDTO } from './order-item-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionDTO } from './transaction-dto';

/**
 * 
 * @export
 * @interface OrderDTO
 */
export interface OrderDTO {
    /**
     * 
     * @type {number}
     * @memberof OrderDTO
     */
    'id'?: number;
    /**
     * 
     * @type {CompactUserDTO}
     * @memberof OrderDTO
     */
    'user'?: CompactUserDTO;
    /**
     * 
     * @type {string}
     * @memberof OrderDTO
     */
    'status'?: StatusEnum;
    /**
     * 
     * @type {number}
     * @memberof OrderDTO
     */
    'totalAmount'?: number;
    /**
     * 
     * @type {Array<OrderItemDTO>}
     * @memberof OrderDTO
     */
    'items'?: Array<OrderItemDTO>;
    /**
     * 
     * @type {TransactionDTO}
     * @memberof OrderDTO
     */
    'transaction'?: TransactionDTO;
    /**
     * 
     * @type {string}
     * @memberof OrderDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDTO
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrderDTO
     */
    'canEdit'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrderDTO
     */
    'canCancel'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrderDTO
     */
    'canPay'?: boolean;
}

export const StatusEnum = {
    PENDING: 'PENDING',
    HISTORIC: 'HISTORIC'
} as const;

export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];


