/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageableObject } from './pageable-object';
// May contain unused imports in some cases
// @ts-ignore
import type { SortObject } from './sort-object';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionAuditDTO } from './transaction-audit-dto';

/**
 * 
 * @export
 * @interface PageTransactionAuditDTO
 */
export interface PageTransactionAuditDTO {
    /**
     * 
     * @type {number}
     * @memberof PageTransactionAuditDTO
     */
    'totalElements'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageTransactionAuditDTO
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageTransactionAuditDTO
     */
    'size'?: number;
    /**
     * 
     * @type {Array<TransactionAuditDTO>}
     * @memberof PageTransactionAuditDTO
     */
    'content'?: Array<TransactionAuditDTO>;
    /**
     * 
     * @type {number}
     * @memberof PageTransactionAuditDTO
     */
    'number'?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageTransactionAuditDTO
     */
    'sort'?: SortObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageTransactionAuditDTO
     */
    'first'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageTransactionAuditDTO
     */
    'last'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageTransactionAuditDTO
     */
    'numberOfElements'?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageTransactionAuditDTO
     */
    'pageable'?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageTransactionAuditDTO
     */
    'empty'?: boolean;
}

