/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompactUserDTO } from './compact-user-dto';

/**
 * 
 * @export
 * @interface ReportStatusDTO
 */
export interface ReportStatusDTO {
    /**
     * 
     * @type {number}
     * @memberof ReportStatusDTO
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReportStatusDTO
     */
    'reportType'?: ReportTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ReportStatusDTO
     */
    'status'?: StatusEnum;
    /**
     * 
     * @type {CompactUserDTO}
     * @memberof ReportStatusDTO
     */
    'requestedBy'?: CompactUserDTO;
    /**
     * 
     * @type {string}
     * @memberof ReportStatusDTO
     */
    'dateFrom'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportStatusDTO
     */
    'dateTo'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ReportStatusDTO
     */
    'parameters'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof ReportStatusDTO
     */
    'fileUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportStatusDTO
     */
    'fileName'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReportStatusDTO
     */
    'fileSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReportStatusDTO
     */
    'mimeType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportStatusDTO
     */
    'errorMessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportStatusDTO
     */
    'requestedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportStatusDTO
     */
    'completedAt'?: string;
}

export const ReportTypeEnum = {
    DAILY_SALES: 'DAILY_SALES',
    WEEKLY_SALES: 'WEEKLY_SALES',
    MONTHLY_SALES: 'MONTHLY_SALES',
    DETAILED_FINANCIAL: 'DETAILED_FINANCIAL',
    TRANSACTION_HISTORY: 'TRANSACTION_HISTORY',
    DAILY_MEAL_REPORT: 'DAILY_MEAL_REPORT',
    WEEKLY_MEAL_REPORT: 'WEEKLY_MEAL_REPORT',
    ORDER_SUMMARY: 'ORDER_SUMMARY',
    CANCELLED_ORDERS: 'CANCELLED_ORDERS',
    DELIVERY_SCHEDULE: 'DELIVERY_SCHEDULE',
    USER_ACTIVITY: 'USER_ACTIVITY',
    LOGIN_HISTORY: 'LOGIN_HISTORY',
    MENU_PERFORMANCE: 'MENU_PERFORMANCE',
    ALLERGEN_REPORT: 'ALLERGEN_REPORT',
    NUTRITIONAL_SUMMARY: 'NUTRITIONAL_SUMMARY',
    SYSTEM_USAGE: 'SYSTEM_USAGE',
    NOTIFICATION_HISTORY: 'NOTIFICATION_HISTORY',
    CUSTOM: 'CUSTOM'
} as const;

export type ReportTypeEnum = typeof ReportTypeEnum[keyof typeof ReportTypeEnum];
export const StatusEnum = {
    REQUESTED: 'REQUESTED',
    PROCESSING: 'PROCESSING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    EXPIRED: 'EXPIRED'
} as const;

export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];


