/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to scan a user barcode for delivery
 * @export
 * @interface ScanUserBarcodeRequest
 */
export interface ScanUserBarcodeRequest {
    /**
     * The scanned user barcode/credential number
     * @type {string}
     * @memberof ScanUserBarcodeRequest
     */
    'barcode': string;
}

