/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to scan an item barcode for delivery confirmation
 * @export
 * @interface ScanItemBarcodeRequest
 */
export interface ScanItemBarcodeRequest {
    /**
     * The user\'s barcode/credential number
     * @type {string}
     * @memberof ScanItemBarcodeRequest
     */
    'userBarcode': string;
    /**
     * The order item ID to mark as delivered
     * @type {number}
     * @memberof ScanItemBarcodeRequest
     */
    'orderItemId': number;
}

