/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompactUserDTO } from './compact-user-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionDTO } from './transaction-dto';

/**
 * 
 * @export
 * @interface TransactionAuditDTO
 */
export interface TransactionAuditDTO {
    /**
     * 
     * @type {number}
     * @memberof TransactionAuditDTO
     */
    'id'?: number;
    /**
     * 
     * @type {Array<TransactionDTO>}
     * @memberof TransactionAuditDTO
     */
    'transactions'?: Array<TransactionDTO>;
    /**
     * 
     * @type {number}
     * @memberof TransactionAuditDTO
     */
    'transactionCount'?: number;
    /**
     * 
     * @type {CompactUserDTO}
     * @memberof TransactionAuditDTO
     */
    'compactUser'?: CompactUserDTO;
    /**
     * 
     * @type {string}
     * @memberof TransactionAuditDTO
     */
    'loadedContent'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionAuditDTO
     */
    'transactionAuditType'?: TransactionAuditTypeEnum;
}

export const TransactionAuditTypeEnum = {
    LOAD_SINGLE: 'LOAD_SINGLE',
    BULK_CREDIT_LOAD: 'BULK_CREDIT_LOAD',
    REFUND: 'REFUND',
    ADMIN_ADJUSTMENT: 'ADMIN_ADJUSTMENT'
} as const;

export type TransactionAuditTypeEnum = typeof TransactionAuditTypeEnum[keyof typeof TransactionAuditTypeEnum];


