/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TransactionWithUserDTO
 */
export interface TransactionWithUserDTO {
    /**
     * 
     * @type {number}
     * @memberof TransactionWithUserDTO
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionWithUserDTO
     */
    'debit'?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionWithUserDTO
     */
    'credit'?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionWithUserDTO
     */
    'runningBalance'?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionWithUserDTO
     */
    'transactionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionWithUserDTO
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionWithUserDTO
     */
    'accountOwnerName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionWithUserDTO
     */
    'accountOwnerEmail'?: string;
}

