/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateUserProfileRequest
 */
export interface UpdateUserProfileRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateUserProfileRequest
     */
    'campusId'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateUserProfileRequest
     */
    'residenceId'?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateUserProfileRequest
     */
    'allergyIds'?: Array<number>;
}

