/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompactUserDTO } from './compact-user-dto';

/**
 * 
 * @export
 * @interface UserSettingsDTO
 */
export interface UserSettingsDTO {
    /**
     * 
     * @type {number}
     * @memberof UserSettingsDTO
     */
    'id'?: number;
    /**
     * 
     * @type {CompactUserDTO}
     * @memberof UserSettingsDTO
     */
    'user'?: CompactUserDTO;
    /**
     * 
     * @type {boolean}
     * @memberof UserSettingsDTO
     */
    'pushEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserSettingsDTO
     */
    'emailEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserSettingsDTO
     */
    'orderUpdates'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserSettingsDTO
     */
    'menuUpdates'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserSettingsDTO
     */
    'accountUpdates'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserSettingsDTO
     */
    'promotional'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserSettingsDTO
     */
    'systemAnnouncements'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserSettingsDTO
     */
    'quietHoursStart'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSettingsDTO
     */
    'quietHoursEnd'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSettingsDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSettingsDTO
     */
    'updatedAt'?: string;
}

