/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompactUserDTO } from './compact-user-dto';

/**
 * 
 * @export
 * @interface UserEventAuditDTO
 */
export interface UserEventAuditDTO {
    /**
     * 
     * @type {number}
     * @memberof UserEventAuditDTO
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserEventAuditDTO
     */
    'timestamp'?: string;
    /**
     * 
     * @type {CompactUserDTO}
     * @memberof UserEventAuditDTO
     */
    'user'?: CompactUserDTO;
    /**
     * 
     * @type {string}
     * @memberof UserEventAuditDTO
     */
    'type'?: TypeEnum;
}

export const TypeEnum = {
    LOGIN: 'LOGIN',
    LOGOUT_IMPLICIT: 'LOGOUT_IMPLICIT',
    LOGOUT_EXPLICIT: 'LOGOUT_EXPLICIT',
    TOKEN_REFRESH: 'TOKEN_REFRESH',
    REGISTER: 'REGISTER',
    PROFILE_CREATED: 'PROFILE_CREATED',
    PROFILE_UPDATED: 'PROFILE_UPDATED',
    DETAILS_UPDATE: 'DETAILS_UPDATE',
    SETTINGS_UPDATED: 'SETTINGS_UPDATED',
    ORDER_CREATED: 'ORDER_CREATED',
    ORDER_CANCELLED: 'ORDER_CANCELLED',
    FEEDBACK_SUBMITTED: 'FEEDBACK_SUBMITTED',
    ADMIN_USER_CREATED: 'ADMIN_USER_CREATED',
    ADMIN_USER_UPDATED: 'ADMIN_USER_UPDATED',
    ADMIN_USER_DELETED: 'ADMIN_USER_DELETED',
    ADMIN_DETAILS_UPDATE: 'ADMIN_DETAILS_UPDATE',
    ADMIN_ORDER_STATUS_UPDATED: 'ADMIN_ORDER_STATUS_UPDATED',
    ADMIN_ORDER_ITEM_STATUS_UPDATED: 'ADMIN_ORDER_ITEM_STATUS_UPDATED',
    ADMIN_BULK_ORDER_STATUS_UPDATED: 'ADMIN_BULK_ORDER_STATUS_UPDATED',
    ADMIN_MENU_CREATED: 'ADMIN_MENU_CREATED',
    ADMIN_MENU_UPDATED: 'ADMIN_MENU_UPDATED',
    ADMIN_MENU_DELETED: 'ADMIN_MENU_DELETED',
    ADMIN_MENU_TEMPLATE_CREATED: 'ADMIN_MENU_TEMPLATE_CREATED',
    ADMIN_MENU_TEMPLATE_UPDATED: 'ADMIN_MENU_TEMPLATE_UPDATED',
    ADMIN_MENU_TEMPLATE_DELETED: 'ADMIN_MENU_TEMPLATE_DELETED',
    ADMIN_NOTIFICATION_SENT_TO_ALL: 'ADMIN_NOTIFICATION_SENT_TO_ALL',
    ADMIN_NOTIFICATION_SENT_TO_USER: 'ADMIN_NOTIFICATION_SENT_TO_USER'
} as const;

export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];


