###
GET http://localhost:8080/api/admin/users

###
GET http://localhost:8080/api/admin/users/{{id}}

###
PUT http://localhost:8080/api/admin/users/{{id}}

###
DELETE http://localhost:8080/api/admin/users/{{id}}

