/* tslint:disable */
/* eslint-disable */
/**
 * Spys API
 * REST API for Spys
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/admin-allergy-management-api';
export * from './api/admin-audit-api';
export * from './api/admin-campus-management-api';
export * from './api/admin-feedback-api';
export * from './api/admin-finance-api';
export * from './api/admin-menu-api';
export * from './api/admin-menu-templates-api';
export * from './api/admin-notifications-api';
export * from './api/admin-order-management-api';
export * from './api/admin-reports-api';
export * from './api/admin-residence-management-api';
export * from './api/admin-user-management-api';
export * from './api/authentication-api';
export * from './api/delivery-admin-api';
export * from './api/list-api';
export * from './api/notifications-api';
export * from './api/user-account-api';
export * from './api/user-feedback-api';
export * from './api/user-menu-api';
export * from './api/user-orders-api';
export * from './api/user-profile-api';
export * from './api/user-settings-api';

