spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=postgres
spring.datasource.password=supersecret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.out-of-order=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spys.demoData.enabled=false
spys.demoData.seedWeeks=12
spys.demoData.rogueAdmin.enabled=true

# JWT Configuration
app.jwt.secret=${JWT_SECRET_KEY:MzdmNTU4MTM0YmFhNTM1OTAzYzZhODg5MzFjODEyMmUzMzQzNjhiZjk1MWYyY2FkYTU2OWIxMTc3NGVmOTc5NWVmNmQyYWM5NjFkMTNlZTQ0YTBjODM3ZGIzODE3YmI5ZGI2OGFjM2JkZmI4YjE5YTEzMDg2MTg0ODRhOWRhOGY=}
app.jwt.expiration-ms=900000

# Refresh Tokens
app.refresh-token.expiration-ms=604800000
app.refresh-token.max-per-user=5

# Security Configuration
logging.level.org.springframework.security=DEBUG

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/api/docs/api-docs
springdoc.swagger-ui.path=/api/docs/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

# VAPID keys for Web Push Notifications
# Replace with your own generated keys
vapid.public.key=BAhwCZrog43HXeotvGJbo_WbLu94UKxd6rTI_LRkcxJp8eO66UqGO2AXnDCsIXdVCDl2hVUvyYZjPnm6HpmVDLM
vapid.private.key=1ZO1zYQ7OGkVesKodfoQl_KxO4dAnV0SZ1n92zZjS8E

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.endpoint.prometheus.access=unrestricted