package com.jel.spys.entity;

public enum ReportType {
    DAILY_SALES,
    WEEKLY_SALES,
    MONTHLY_SALES,
    DETAILED_FINANCIAL,
    TRANSACTION_HISTORY,
    
    DAILY_MEAL_REPORT,
    WEEKLY_MEAL_REPORT,
    ORDER_SUMMARY,
    CANCELLED_ORDERS,
    DELIVERY_SCHEDULE,
    
    USER_ACTIVITY,
    LOGIN_HISTORY,
    
    MENU_PERFORMANCE,
    ALLERGEN_REPORT,
    NUTRITIONAL_SUMMARY,
    
    SYSTEM_USAGE,
    NOTIFICATION_HISTORY,
    CUSTOM
}
